### ISSUE TITLE
Change the URL

### ISSUE THREAD

**Issue by thedittmer** [matt-cook/kiosk#1]
Is there a way to change the URL after I set it the first time. 

Also, does this work well with dual screen mode where you could have two kiosks powered by one chromebox?

**Comment by matt-cook** [comment]
This is now possible without re-install, as of v5.3.0.

**Comment by brandflugan** [comment]
That is great news, thanks a lot!

2015-05-27 20:24 GMT+02:00 Matt Cook <notifications@github.com>:
