### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by ladiver** [matt-cook/kiosk#10]
Is there anyway to allow printing from kiosk?  I have set up Google Cloud Print and it is working.  Just wondering if there was a way to use that same printer in Kiosk mode.  If not, what about a direct connected printer?

We will be using the HP Chromebox with Kiosk, but I need the ability to print from a webpage.

Thanks,

Jeff

![](https://api.bountysource.com/badge/issue?issue_id=6952444)

**Comment by matt-cook** [comment]
@sunnykoundal:

> I am using Kiosk app of chrome and printing is not working in that.
but on other hand if I manually create a kiosk in chrome by changing in property of chrome by adding

> `--kiosk --kiosk-printing --enable-print-preview "http://localhost:55573/"`
into target under shortcut tab.

 > Its working fine for me.

**Comment by sunnykoundal** [comment]
@matt-cook 
Thanks to draw me here, Actually I already visited this link. I am using same `window.print();` in my application, but no luck in kiosk app. I am able to do in chrome by manually change in properties as I mentioned in my thread [#152](https://github.com/matt-cook/kiosk/issues/152). I hope you understand my issue.

**Comment by matt-cook** [comment]
Request by a user via email on March 15, 2017.

**Comment by pvhung1** [comment]
Hi, I'try added windows.print() but it can not show webview after read URL , it show only html page.

**Comment by matt-cook** [comment]
Unfortunately, silent printing doesn't seem to be possible on all platforms. However, optionally printing via CTRL+P and the standard dialog will be available in version 5.11.0: https://github.com/matt-cook/kiosk/issues/10
