### ISSUE TITLE
add ability to inject js/css

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#100]
specified in Kiosk admin, injected into browser.html `<webview>`

**Comment by Moka51** [comment]
Hello! How can I inject my own CSS code?

**Comment by RDumais** [comment]
Can you please expand on this, Matt? I am currently using a chrome extension to inject javascript and css into a html, which works great. I have a .js file, a .css file, and a manifest file in my extension. How would I be able to inject the javascript and css into the url loaded by the kiosk app? I have enabled 'Serve Local Content' and loaded the Chrome Extension folder. Any help is appeciated.

![kioskextenion](https://cloud.githubusercontent.com/assets/26531108/24559473/d066e1d6-160c-11e7-8398-aea57dab402d.png)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-ability-to-inject-js-css/130
