### ISSUE TITLE
I cannot get Kiosk to auto-start

### ISSUE THREAD

**Issue by tkrauter** [matt-cook/kiosk#101]
I cannot get Kiosk to auto-start at power-on or reboot

On power-up or reboot the Kiosk app goes into the settings page.  If I enter a URL and click “Save”, it restarts and returns to the settings page.  If I press Control+Alt+S and log-in, I can set the URL and it starts the Kiosk normally.  On reboot it again loops the settings page.
- I have a managed device – ASUS Chromebox CN62
  ChromeOS version 49.0.2623.95
- The device shows up in admin.google.com status=provisioned
- The Kiosk app is configured in Chrome App Management to auto deploy
- The Kiosk app is set to Auto-Launch in Kiosk Settings (under Device Settings)

I don't see anywhere in admin.google.com to add the URL

What am I missing?

Thanks!

**Comment by matt-cook** [comment]
Do you have "Erase all local user data" selected in the management console? If so, please turn this option off, restart twice and try again.

![screen shot 2016-03-30 at 4 44 58 pm](https://cloud.githubusercontent.com/assets/626516/14158700/2c161b64-f697-11e5-9bdb-f2fadd887d4f.png)

**Comment by tkrauter** [comment]
Thanks for responding so quickly.  But, I am not seeing these options in Device Management 
-> Chrome -> Device Settings.  I have seen them once in the past but cannot find them again.

**Comment by tkrauter** [comment]
I have a single app kiosk license.  Should I have the ChromeOS management license instead?  Google documentation says that under the Single App License some configuration options are not available.

**Comment by 1951FDG** [comment]
Looking at the [license features](https://support.google.com/chrome/a/answer/2717664?hl=en), you would only need the Single App License.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/i-cannot-get-kiosk-to-auto-start/134
