### ISSUE TITLE
User-Agent on Remote Schedule Request

### ISSUE THREAD

**Issue by mattzuba** [matt-cook/kiosk#103]
First off, thanks for this awesome app; this will make my organization's life so much easier as we are constantly changing the URLs on the Chromebooks in the Google Admin console for different events, which requires a call to the Service Desk and them to manage it.  Using this, I can allow the end users to manage it themselves in the app that this Kiosk will be loading.

On to my question - I can see the User-Agent setting works for the pages actually loaded via the Kiosk Mode, but not the requests for the Remote Schedule.  Is this intentional?  Overlooked?  Can it be added?

My use-case for this is that I have 32 Chromebooks that will all be using this, and by setting a custom user-agent, I can tell which ones are checking in like they should to help with troubleshooting if necessary.  I've added a GET parameter to my Remote Schedule call in the mean time, but having the user-agent work on the Remote call would be nice too!

**Comment by matt-cook** [comment]
Didn't consider that use case, as you said currently the user agent is only applied to the content page (not the schedule request). 

We're doing the call for the schedule here: https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L25 so it may be pretty simple (http://stackoverflow.com/a/5771947) to set the user agent. We'll test and see if this functionality can be added.

**Comment by matt-cook** [comment]
Unfortunately, even in an app jQuery won't set the user-agent:

![screen shot 2016-04-05 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/626516/14295508/9808749a-fb3b-11e5-863a-76115e0b9a1b.png)

It'll be little more challenging to set for schedule polling. Possible via [chrome.webRequest](https://developer.chrome.com/extensions/webRequest) or [chrome.debugger](http://stackoverflow.com/a/15626197)

**Comment by kzahel** [comment]
WSC now has a nicely working chromesocketxhr.js that works nearly like XMLHttpRequest and lets you set arbitrary headers.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/user-agent-on-remote-schedule-request/137
