### ISSUE TITLE
clarify "inactivity reset" to indicate browser reload, not system restart

### ISSUE THREAD

**Issue by koltzc** [matt-cook/kiosk#106]
We use this in our library where students go to our library portal to look for books. Being students, they just leave the site to wherever they are done searching. We  would love to have a checkbox to enable the feature where it will reload the original website when there is inactivity in the system.

**Comment by matt-cook** [comment]
Glad to hear it's been working for you! It sounds like the existing "Inactivity Reset" feature should accomplish what you need. Have you tried this?

**Comment by koltzc** [comment]
I wasn't sure if it would reset the device or just reset the URL. I don't want it resetting the device throughout the day from inactivity. That is why I posted this.

**Comment by matt-cook** [comment]
Good point, we do need to clarify that wording. The inactivity reset only reloads the browser, it does not restart the device entirely: https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L153-L158

**Comment by koltzc** [comment]
Awesome, thank you!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/clarify-inactivity-reset-to-indicate-browser-reload-not-system-restart/127
