### ISSUE TITLE
add option to clear cookies/data on inactivity resest

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#111]
As reported in Chrome Web Store:

> I personally dont think it should maintain cookies. This does not work well with multiple users signing in at different times.

**Comment by mcwebb** [comment]
+1 on this, our usecase is that the kiosk accesses a booking site. Without removing cookies the previous user's details readable.
For us, it would also be useful to optionally delete cookies whenever navigating to a specific url (particularly the defined home page)

**Comment by keyboy777** [comment]
Agreed with those guys^^^

**Comment by mfkp** [comment]
Just put $25 behind this one if anyone is interested: https://www.bountysource.com/issues/33440269-add-option-to-clear-cookies-data-on-inactivity-resest

Otherwise I'll probably take a crack at it in a week or two.
