### ISSUE TITLE
Google OS problem

### ISSUE THREAD

**Issue by eredeli** [matt-cook/kiosk#115]
We have one problem on Google OS (model: ASUS CHROMEBOX-M004U Desktop). We can't touch, on touchscreen monitor Google Map. We cant move map with touch and click on pins. there is no function for it. On Windows 7 is working perfect (we tested it). Please Help. Thanks

**Comment by kstangel** [comment]
Your touchscreen may not be compatible with Chrome OS. We have seen issues where the touchscreen need to be configured to work with the Chrome Device. Please check with the manufacture of your touchscreen device.

**Comment by eredeli** [comment]
We was thinking about this version too... everything is working well on Google Map, only Kiosk App have problems with map. Screen is working well with Google Chrom & Map

**Comment by eredeli** [comment]
Any idea?

**Comment by matt-cook** [comment]
Possibly related to #96, #122, #116

**Comment by eredeli** [comment]
Thanks. i will chk now.

**Comment by eredeli** [comment]
Nope... its not... :(

**Comment by matt-cook** [comment]
On the bottom right of the map does it say "lite mode"? 

I noticed https://maps.google.com switched on lite mode for me automatically at one point in the Kiosk app. Drag appeared to be working with lite mode off, but not when it is on.

https://support.google.com/maps/answer/3031966?hl=en

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/google-os-problem/126
