### ISSUE TITLE
touch input stops working

### ISSUE THREAD

**Issue by dfmstevens** [matt-cook/kiosk#116]
We use the Kiosk app for several months in a retail environment now. We noticed that the screens randomely 'freeze'. It looks like the touch driver get's disabled. When we connect a phisical keyboard/mouse we can access the admin console for the Kiosk (ctrl+A). Any idea how to solve this?

**Comment by matt-cook** [comment]
Does your content freeze? or only touch functionality is lost? This could be related to #96 or #122

**Comment by dfmstevens** [comment]
Dear Matt,

Thanks for your reply. It looks like only the touch functionality get's
lost. When I connect a USB keyboard/mouse to the terminal when it's
'frozen' i can control it again. The touchscreen will only work after a
reboot.

Regards,

Dan Stevens
+971 5 26236848

**Comment by anneris** [comment]
We're having the same problem - no more touches.  Clicks can be made via remote desktop / Teamviewer but not via the touchscreen itself (Displax touch controller on USB).  Moreover, the touch hardware itself still works - as witnessed by the windows "ripples" on a touch event - there is just no reaction from the browser.  

So I am suspecting a Chrome problem?

**Comment by dfmstevens** [comment]
Hi Anner,

We think the issue is that the Kiosk handles queuing different then your
browser. We worked out that have DB queries freeze the screen. We changed
our DB structure and optimized sql and the problems seem to be solved.
We've never been able to reproduced the issue in the browser.

Regards,

Dan Stevens
+971 5 26236848

**Comment by celron** [comment]
I am having problems similar to what is described in the beginning of this issue by @dfmstevens and by @anneris.  This app becomes unresponsive, however if I connect using something like teamviewer, that works and touch is also restored.  

I notice that the response can at sometimes become delayed, so I suspect it might be something to do with event queue/blocking.

I have been able to decrease the problem when I changed the way some events using setInterval works or remove, however the 'freezing' still happens.

Is @dfmstevens correct in that queueing is handled differently in kiosk?

**Comment by anneris** [comment]
We had succes in solving this issue by making sure that the Chrome flag "Enable touch events" was set to enable instead of automatic.

It's a hard problem to troubleshoot, but ever since we did not encounter any more unresponsiveness from touch input after a while.

**Comment by dfmstevens** [comment]
@celron Since we changed the way we query the DB we haven't seen the issue again. The event handling happens in a more logical way now. I think the Chrome boxes are not good in queuing events.

@anneris We've played with that setting as well and still randomly the issue came up.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/touch-input-stops-working/132
