### ISSUE TITLE
Serve Local Content User different then ChromeOS user

### ISSUE THREAD

**Issue by beardedbrew** [matt-cook/kiosk#118]
When I go to serve local content, there is only a download folder and no files that exist for my current user.

What user does the Kiosk use? And how do I move files into this directory?

**Comment by matt-cook** [comment]
Good question, I had assumed it uses the currently logged in user. Will need to confirm this.

**Comment by athedrummaster** [comment]
I am seeing the same as beardedbrew. I have a chromebit set up as a single app kiosk and it starts into the app at boot automatically. When I try to serve local content, it only shows the downloads folder. Which user is this referring to?

**Comment by JayGoldberg** [comment]
It definitely is not running as the user who set up developer mode and added Kiosk to autostart at boot, as I don't have any of my login sessions in the context the app runs in in single app kiosk.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/serve-local-content-user-different-then-chromeos-user/121
