### ISSUE TITLE
Add support for PDF pop-ups

### ISSUE THREAD

**Issue by rocmartin2003** [matt-cook/kiosk#128]
We are using a web based ERP system and your app works perfectly for getting users to the page they are only allowed to go to, but my issue is, once we get them to that page, there is a button for work instructions that they need to access that pops up a PDF file for them to read. The app prevents that pop up from happening, since it's only allowing the kiosk mode to work for the website. Is there any way to allow that popup in the app?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-support-for-pdf-pop-ups/135
