### ISSUE TITLE
deployment in bulk

### ISSUE THREAD

**Issue by horusluviman** [matt-cook/kiosk#131]
Is there a way in which I can deploy a URL in bulk throughout several Chromebits and force a signed in to avoid going one by one repeating the same procedure, if there is no workaround I would understand it, but I will appreciate an answer from you guys!

**Comment by jminne** [comment]
yes, this would be great.

**Comment by jonathanlewis84** [comment]
Yes, some way to do this en mass would be ideal.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/deployment-in-bulk/133
