### ISSUE TITLE
Managed group of kiosk - Scheduler, cookies, and remote admin wish list

### ISSUE THREAD

**Issue by tumbulwead** [matt-cook/kiosk#133]
Hi there,

Your app is great.  This is a bit of a wish list, but I'm about to use it to deploy 14 kiosks at the Museum of Anthropology at the University of British Columbia, and it's 99% there.  It works better than Chrome Sign Builder for us for 2 reasons: It persists user-specific chrome settings to allow flash to always run across restarts (which sign builder doesn't do with public sessions); We need to store a cookie on each device that identifies it as pertaining to one region in that section of the gallery (for mapping items and such) across restarts as well.  Yours is the only app that I can find for Chrome OS to do these 2 things. 

Others asking about removing this is opposite what we would need - please consider that as optional if possible.  

One thing that would be helpful is the ability to set it to sleep after hours (we're closed between 9pm and 9am).  

Finally, I used to be able to watch all 14 catalogues (via thumbnails) remotely (and control them with ARD) when they ran via mac minis, and I'll lose that with these.  If your app could build that into remote management, I've seen a number of people looking for that functionality, when they deal with kiosks across an enterprise that are managed remotely.  

Thanks for a great app, and feel free to message or contact me directly.  We'd love to work with you on any of the above, if you wanted to list us as users of your app. 

Thanks very much!

Kenny Pierce
I.T. Manager, UBC Museum of Anthropology

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/managed-group-of-kiosk-scheduler-cookies-and-remote-admin-wish-list/117
