### ISSUE TITLE
F1 opens Chrome-Help and allows to browse anywhere

### ISSUE THREAD

**Issue by Thomas9876** [matt-cook/kiosk#136]
In kiosk mode, the keyboard shortcut "F1" is still enabled to access chrome's help dialogue. From there it is possible to browse everywhere. Is it posible to block this possibility?

Kiosk: 5.8.2
Chrome: 52.0.2743.116 m (64-bit)
OS: Win7

Thank you very much
Thomas

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/f1-opens-chrome-help-and-allows-to-browse-anywhere/47
