### ISSUE TITLE
Local admin login dialog allows right click and access lo local disk

### ISSUE THREAD

**Issue by Thomas9876** [matt-cook/kiosk#137]
After pressing Ctrl + A it is possible to do a right click into the password field. From there it is possible to access the language settings which opens a standard chrome. From there it is possible to open an explorer.

Kiosk: 5.8.2
Chrome: 52.0.2743.116 m (64-bit)
OS: Win7

Thanks a lot
Thomas

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/local-admin-login-dialog-allows-right-click-and-access-lo-local-disk/46
