### ISSUE TITLE
remote management inaccessible on ChromeOS

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#14]
Documented issue with ChromeOS: https://code.google.com/p/chromium/issues/detail?id=233052

**Comment by matt-cook** [comment]
related issue: https://code.google.com/p/chromium/issues/detail?id=435404

**Comment by matt-cook** [comment]
For now it appears the only solution is to switch to developer mode: http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/asus-chromebox#TOC-Developer-Mode

and open the port manually via:  https://code.google.com/p/chromium/issues/detail?id=233052#c6

**Comment by matt-cook** [comment]
Additional details reported by a user:

> By changing the Remote Administration Host address to the wlan0 IPv4 option and changing the Port from 80 to 8080, I was able to get it to work.  The standard loopback address on port 8080 won’t work, nor will the IPv4 wlan0 address on port 80.

**Comment by taneth111** [comment]
Confirmed working by changing the port to 8080 from a remote device.

**Comment by matt-cook** [comment]
Confirmed working on 8080 here as well. Did NOT work with 80 or 82. I don't see any documentation on which ports are blocked or how to tell if opening the port was successful: https://developer.chrome.com/apps/sockets_tcpServer

Default will be changed to 8080.

**Comment by backslashgithub** [comment]
"By changing the Remote Administration Host address to the wlan0 IPv4 option and changing the Port from 80 to 8080, I was able to get it to work."
I can log in and edit and save, only when i want to restart kiosk crashes on the remote host.
anybody ?

**Comment by matt-cook** [comment]
@backslashgithub thanks for reporting these bugs. I'll be investigating for the next release.

**Comment by michaelvelasquez** [comment]
Hello. I want to report similar results to @backslashgithub 
I have Remote Administration working on an ASUS Chromebit on port 8080 on both my local network and from outside my network with port forwarding. I can log in, edit and save. When I Restart, the Kiosk Remote Admin page shows a "Restarting" message and then comes back up again, but Kiosk doesn't restart on the Chromebit. It doesn't crash, but nothing happens.  If I manually restart Kiosk on the Chromebit, my edited URL displays so it is being saved. I tested using Remote Admin via Chrome on OS X 10.11.6 and Safari on OS X 10.6.8 (those are just the OS versions I have on hand). Thank you.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/remote-management-inaccessible-on-chromeos/93
