### ISSUE TITLE
how to serve a single page from local computer?

### ISSUE THREAD

**Issue by bbrink-MN** [matt-cook/kiosk#140]
Hi Matt,

I am stuck trying to serve a single page from my local computer. For example: 

c:\MyHTMLDirectory\MyDoc.html

I leave the default content url as 
http://127.0.0.1:8080/

check the box for "local content" and then set the directory to MyHTMLDirectory

When I launch kiosk I see two links, one for parent and another for MyDoc.html   -I'd like to see MyDoc.html displayed in full glory. 

What am I missing?

thanks in advance,

Bob

**Comment by bbrink-MN** [comment]
Matt,

p.s when I open the page in chrome the URL shown is  file:///C:/MyHTMLDirectory/MyDoc.html

**Comment by matt-cook** [comment]
You should be able to use `http://127.0.0.1:8080/MyDoc.html` as the content URL once you've set the app to serve `C:/MyHTMLDirectory/` via "Serve Local Files"
