### ISSUE TITLE
Won't save settings in Kiosk mode.

### ISSUE THREAD

**Issue by bgappa** [matt-cook/kiosk#144]
We have been using this app on Chrome OS in Kiosk mode (launches from the login screen) for several months.  It worked great until yesterday.

Now every time it is launched it just goes to the settings.  We have had multiple people try multiple times to fill this out and save the results.  When you click save the app closes.  When it is reopened it always goes back to the settings.  It never launches to the URL that was specified in the settings.

If you login to the Chromebook and install the app into the chrome browser it can be configured and saved. The next time it is launched it goes to the web page that was specified. 

As I said we had been using this for several months and never had a problem until yesterday.  One of the machines that we are now testing on didn't have the app available until this morning so it would have installed the latest version.

**Comment by ev5unleash** [comment]
Having the same issue. Attempting to add this as an auto-open type of deal with our Chromebooks but the settings fail to save. I'm guessing that it is unsupported or that we require guidance on how to write up a JSON configuration file for this app.

**Comment by mikesteiner99** [comment]
Yes... Please an Manual !! :-)

**Comment by mobione** [comment]
I am also using Device Management and using 'Auto-Launch Kiosk App' and having the same problem:
Whenever i try to save the settings in the KIOSK app... settings are not saved and it returns to settings page. Any idea what could be wrong?

**Comment by bgappa** [comment]
Ours ended up being a setting in our domain.  We don’t store data on most of our student machines so they are set accordingly.  That setting got applied to the Kiosk machines by accident.  When I got it set to save data it began working again.

Brian Gappa
Enterprise Client Technology Services
Jefferson County Public Schools
303-982-6907

**Comment by mobione** [comment]
Thanks bgappa!

Works now!
I changed the setting:
Device Settings > Sign-in Settings > User Data > Do not erase all local user data

Hope it helps others :)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/wont-save-settings-in-kiosk-mode/91
