### ISSUE TITLE
Inactivity reset reverts to previous target

### ISSUE THREAD

**Issue by johnwhirsch** [matt-cook/kiosk#145]
I have a kiosk setup on Windows 10 using remote admin to update what page it is targeting for content. When I save a new target the kiosk updates immediately like it should but after the inactivity timer times out it reloads the old content again. If I save a new target remotely and then restart the kiosk from the remote admin page immediately the changes do not revert after the inactivity time out.

Side note: I love the app, thank you for making it!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/inactivity-reset-reverts-to-previous-target/115
