### ISSUE TITLE
Can use  the multi-touch function to Zoom-in/out  on touchscreen 

### ISSUE THREAD

**Issue by Cjdef** [matt-cook/kiosk#146]
Hello,

 I'm displaying a web page on a touchscreen(Hardware is Chrome BOX/ browser is Chrome), and cannot use the multi-touch function to Zoom-in/out. 
Have any setting I can use to on those functions?

You can test  with the http://buyingguide.sakura.com.tw

**Comment by matt-cook** [comment]
Thanks for the request, this is a duplicate of the request here: https://github.com/matt-cook/kiosk/issues/31 so we can continue the discussion there.
