### ISSUE TITLE
How to launch Kisok Mode form the terminal?

### ISSUE THREAD

**Issue by Philluminati** [matt-cook/kiosk#147]
I am using chromium. I want to start a Website in Kiosk Mode from the terminal.
I know that there are commands like "chromium-browser --kiosk http://example.com", but are there some more other Flags that i can, for example, hide the cursor?
So for example, "chromium-browser --kiosk **--hidecursor** http://example.com"
I need to autostart kiosk mode after bootup, and i want to hide the cursor at the Website.

thanks for help.

**Comment by matt-cook** [comment]
If you are using the kiosk app, you should be able to put it in the Startup folder on windows, Login Items on OSX, or set the device to Kiosk mode if you are using ChromeOS.

**Comment by dcee66** [comment]
I am using chromium under Ubuntu 16. Autostart the browser is no problem but it do not start in kiosk mode the command line works, but the system do not remind it after restart.
thanks for help
