### ISSUE TITLE
Google Presentations via URL - Error with slide transitions

### ISSUE THREAD

**Issue by OliviaRNSH** [matt-cook/kiosk#148]
I am utilising the Kiosk to play my google presentation at the moment - my URL code is for slides to be 30 seconds each. I have tested the URL in a regular browser, and all is fine, however when the URL is inserted into the kiosk, that timing is overridden, and slides almost change instantly & constantly. Can you tell me how I can fix this, as it seems to be only defective when using the kiosk?
TIA

**Comment by matt-cook** [comment]
Can you provide an example URL?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/google-presentations-via-url-error-with-slide-transitions/110
