### ISSUE TITLE
Proposed change to remote schedule server request url

### ISSUE THREAD

**Issue by PeterGrace** [matt-cook/kiosk#149]
Hi there!

I'm the author of [pi_director](https://github.com/PeterGrace/pi_director), a project that enables people to use Raspberry Pis as digital signage.  I'd love to add functionality into my project that allows people to control the schedule of chrome devices that are running your Kiosk app, but my software considers each display as a single, standalone unit.  

Your Remote Schedule Server code seems to be almost exactly what I need, but I need a way to differentiate individual devices.  Would you be tolerant to a pull request which would amend 
[this line of code](https://github.com/matt-cook/kiosk/blob/2237c4d073e94840a3c5428e3c58f42f659c1494/src/js/browser.js#L134) to suffix a unique identifier (mac address, MEID, some unique discriminator) to the end of the url?

**Comment by trevoriancox** [comment]
I don't use the scheduleURL as we have our own system for that, but I configure each device using policy to have a unique URL that includes the computer name. If you just have a random number or MAC address that's not as user-friendly for managing the display devices.

**Comment by PeterGrace** [comment]
Thanks for your feedback.  I already have a fully functioning UI/dashboard for managing standalone digital signage kiosks, I just need a unique identifier to manage each one.  I'm intending to enable the users of my project to use chromebits, being able to continue to use the environment they already have installed for managing their Pis.  

To this end, I need to have a unique identifier in the request URL so that my api endpoint can figure out which device is requesting its schedule/

**Comment by PeterGrace** [comment]
Nevermind: http://stackoverflow.com/questions/15554299/how-do-you-get-the-device-name-or-hostname-from-a-chrome-extension/15556829#15556829
