### ISSUE TITLE
rotate screen of 90 degree

### ISSUE THREAD

**Issue by matteoraggi** [matt-cook/kiosk#154]
This app is disabling the FLIP THIS extension, and I can't rotate the pages of 90 degree while usign this fullscreen app.
https://chrome.google.com/webstore/detail/flip-this/donljlliiecjcagcenoeohjmabfegkph
Could you please patch the compatibility issue, or add the automatic 90 degree screen rotation to your app?
I made tests with raspberry pi 3 model B and raspbian 8 and chromium 51.

**Comment by matt-cook** [comment]
I assume you're unable to set the rotation on the actual display or via the drives on the raspberry pi? this would be the preferred method. We don't be able to enable compatibility with an extension, so this would be a new feature request.

**Comment by matteoraggi** [comment]
I was not expert in raspberry, now I am able to do it, thanks!
