### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by nithiz** [matt-cook/kiosk#157]
With the new update which brings support for tabs all existing kiosk instances stopped working. This causes problems for over 50 of our clients. Is there any way you could release a hotfix to keep supporting the already running systems so we won't have to reconfigure all the chrome devices by hand?

Thanks in advance.

**Comment by allencoin** [comment]
What's the temporary fix right now? I'm having the same problem. Does it just need to be re-launched?

**Comment by nithiz** [comment]
Closing this issue since it's the same problem as: https://github.com/matt-cook/kiosk/issues/158
