### ISSUE TITLE
[URGENT] Kiosk extension fails to save a URL

### ISSUE THREAD

**Issue by dimak72** [matt-cook/kiosk#159]
Latest Chrome Browser v55 and v54
Windows 7 64 bit
Mac OS 10.11.6
Kiosk extension 5.9.3

steps to reproduce
1) download and install extension
2) click extension to open in admin mode
3) enter url (http://www.google.com)
4) enter local admin password
5) save

Observe: white page

6) ctrl-a to open the extension

Observe: http field is not populated

**Comment by welrachid** [comment]
Did you try to actually press "enter" after writing the url?

**Comment by dimak72** [comment]
I did and it did not work. reinstalled the extension and it works now. probably a user error.
