### ISSUE TITLE
lock to specific domain

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#16]
don't allow users to browse away from specific domain

![](https://api.bountysource.com/badge/issue?issue_id=8295875)

**Comment by matt-cook** [comment]
Could also use specific URL list (regex matching?). Request from Chrome store:

> I am currently using this in a library setting for our Public Catalogs. Works great for the main catalog but users can't click to other sites that are linked from our catalog.

> I am wondering if there is a way to allow a set of URLs so that patrons can get to any of the sites I want them to but not all sites.

**Comment by matt-cook** [comment]
Per request by @zachconstan this could be implemented as a domain whitelist. 

Not currently a development priority.  Feel free to post a bounty (https://www.bountysource.com/issues/8295875-lock-to-specific-domain) or contact us (support@zebradog.com) if you need it implemented.

**Comment by zachconstan** [comment]
Thanks for considering it! I'm muddling by with a kiosk I've cobbled
together, but this addition would make your app hit all the right buttons...

zach

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/lock-to-specific-domain/64
