### ISSUE TITLE
Strange Screen

### ISSUE THREAD

**Issue by phikri** [matt-cook/kiosk#160]
Hi.
We have about 15 screens running with chromebox and zebradog kiosk. this morning some of them had a white screen with the first characters of the URL. https://disp
(the URL is: https://display.edubs.ch/gm1/display)

the reboot was not successful. to enter on the kiosk admin page and press the save button helped.
![img_6697](https://cloud.githubusercontent.com/assets/8354626/20889718/5aa316f8-bb04-11e6-860e-f3564fb38523.JPG)

Regards
Philipp

**Comment by Ben-Maxfield** [comment]
This has been fixed in version 5.9.3, please see this issue i raised this morning.

https://github.com/matt-cook/kiosk/issues/158

**Comment by phikri** [comment]
Super!!!
Thx
