### ISSUE TITLE
URL not loading

### ISSUE THREAD

**Issue by alecmanfre** [matt-cook/kiosk#163]
I just reinstalled kiosk, and when I put the URL in and save I get a blank white page. When I go back into setup, it doesn't seem that the URL saved because it is blank.

**Comment by ericholmer** [comment]
Hi @alecmanfre - try hitting enter after you type the URL. It should then get a "bubble" or tag-style pill around it. Then it should save. A patch is coming that will make this confirmation process automatic.

**Comment by matt-cook** [comment]
This has been fixed in v5.10.0
