### ISSUE TITLE
Chrome Kiosk Not running Local Content Index.html File

### ISSUE THREAD

**Issue by socialpixe** [matt-cook/kiosk#166]
Hello there,

I have develop a basic html application and trying to run in Chrome Kiosk, but unable to run via local content setting. Chrome Kiosk opening in blank screen status. this issue appearing in latest version was non in older ones. 

Please help ASAP.

Thanks in advance.

**Comment by pixelprogrammer** [comment]
I am also experiencing this with version 5.10.1. It appears that the index.html files aren't set to the default index file for the server.

**Comment by exhibitry** [comment]
Same here

**Comment by pixelprogrammer** [comment]
Just wanted to point out that there is a workaround if anyone is looking for one. You can setup your own localhost server with MAMP, XAMPP or manually doing it with Apache or Nginx. Then you can set the Content URL to something like "http://localhost/website" or whatever the url would be. We did this a few times with our company.

**Comment by exhibitry** [comment]
Thanks for a quick response!
