### ISSUE TITLE
how to use remote administration

### ISSUE THREAD

**Issue by Qumle** [matt-cook/kiosk#167]
Hi

Not exactly a bug, but I need some help using the remote administration. I have 3 chromeboxes with Kiosk app showing a webpage. I would like re configure the shown URL from a central Windows machine.

on the support page for the app it simply states:

Remote Administration
On desktop operating systems basic configuration as well as application restart options are available remotely. See "Known Limitations" for details on ChromeOS support.

I cannot see how to actually access this remote adminstration, do I go to a url on the remote machine or do I need a seperate remote desktop app to do this?

I tried accessing
[my ip]:8080 with no response

I enabled remote administration on port 8080 on the chromebox

I hope I am missing something obvious that someone kan direct my attention to

Thanks

Ulrik Lund

**Comment by JayGoldberg** [comment]
Pretty sure you need to do http://`ip_of_chromebox`:8080/ instead. Your local windows machine is not running Kiosk (on port 8080) it runs *on* the machine running Kiosk.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/how-to-use-remote-administration/111
