### ISSUE TITLE
don't reload page when cycling content

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#168]
Load content URL once, then cycle through frames. Use reset interval to trigger reloads.

**Comment by bkfitz** [comment]
This would be awesome thanks!!!

**Comment by tamaker** [comment]
@bkfitz - exactly the same enhancement I need.  Awesome project, would just make it even BETTER!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/dont-reload-page-when-cycling-content/105
