### ISSUE TITLE
Remote admin reboot intermittently not functioning

### ISSUE THREAD

**Issue by athedrummaster** [matt-cook/kiosk#170]
When using remote admin to save site settings and then reboot, the device saves the site just fine but then when reboot button is clicked, the page refreshes but the device does not reboot.

**Comment by Buginsoftware** [comment]
Hi - I'm having the same issue as above, I can save the URL fine but unable to restart to remotely refresh the new page. Please could we have a fix for this please?

**Comment by KSilverman** [comment]
See my solution [here](https://github.com/matt-cook/kiosk/issues/235)

**Comment by matt-cook** [comment]
This issue has been fixed in v5.13.0 (https://github.com/matt-cook/kiosk/pull/256) which was just published in the app store.
