### ISSUE TITLE
graphs no longer rendering

### ISSUE THREAD

**Issue by Webmasterxx1** [matt-cook/kiosk#171]
We have this app running on an Asus Chromebit.
Up until today, the app had been running a website without an issue in the guest mode (unable to access internet proxy).

Since we made a change to the url, the graphs will no longer render.
Our suspicion is that the cache has been cleared - has there been an update to the app that would have done this?
 Is there anyway to store something in the Kiosk cache?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/graphs-no-longer-rendering/108
