### ISSUE TITLE
Hotkey reload? 

### ISSUE THREAD

**Issue by rocmartin2003** [matt-cook/kiosk#172]
We have a web app, that once the link is broken is not reloading. Restarting the kiosk app fixes it, but is there a hotkey sequence we can use to do the reload? Only way I have found to accomplish this is to F5, close it and then restart it.

**Comment by RabsRincon** [comment]
Just to be clear, you refer to a reload as to go back to the initial page(s), right?

**Comment by rocmartin2003** [comment]
Right

**Comment by mfkp** [comment]
I've noticed on my chromebook, I can't seem to reload/refresh pages inside the Kiosk app. There is a dedicated hardware reload button which does nothing, and ctrl+r also does nothing.

I like where this PR is going, but unfortunately the chromebook doesn't have F-keys, so I doubt it would help in this situation.

**Comment by RabsRincon** [comment]
Ey! It's the first notice I have about chromebooks not having F-keys, sorry! Do you have any suggestion about which shortcut could work for chromebooks too?

**Comment by mfkp** [comment]
Let me see if I can figure out what keybinding the chromebook maps to for the reload key.

For reference, this is what the keyboard looks like on my Dell Chromebook 11: 

![dell chromebook 11 keyboard](https://cdn6.bigcommerce.com/s-blhknq8/product_images/uploaded_images/screen-shot-2016-02-29-at-4.29.07-pm.png?t=1456792197)

**Comment by mfkp** [comment]
According to [this article](https://support.google.com/chromebook/answer/1047364?hl=en), the reload button is equivalent to F3.

Would it make more sense to map reload to F3, instead of F7 (which is a screen brightness key on chromebook)?

**Comment by RabsRincon** [comment]
But you refer to the refresh action, right? Or not? Refresh: Load current page again (Usually F5 shortcut on web browsers) Reload: Go to initial pages after (optionally) clearing cache/cookies etc

**Comment by mfkp** [comment]
Ah, got it. I see now that it's different.

Maybe I should file a separate bug for "reloading page not working using reload button or ctrl+r", and you can still have a different hotkey for "resetting back to home page"

**Comment by RabsRincon** [comment]
yeah! Create one so I can create a PR referencing it

**Comment by mfkp** [comment]
@RabsRincon created issue #192
