### ISSUE TITLE
questions about using kiosk

### ISSUE THREAD

**Issue by TheBull50** [matt-cook/kiosk#173]
Good Morning, 

 I just installed the extension on Chrome and it seems to work great. I had a few questions though:

1) Once I load a slide show, how do I change the slide show that is presented. Currently, I use Google slides, publish the slide show and get up up and running that way. However, once it is published, I have no way to edit the content unless I remove the extension and re add. 

2) If I put a link through Google Slides, if I edit it through Google Slides, will the changes go Live instantly?

3) Can I share the slide show with other people and can other have rights to edit the slide show

thanks

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/questions-about-using-kiosk/122
