### ISSUE TITLE
Enhancement request: screensaver

### ISSUE THREAD

**Issue by s-haron** [matt-cook/kiosk#174]
Been using the Kiosk app on a Chromebox as an autolaunch in kiosk mode for a client to use for some touchscreen service
Its been working great, however, would really like to be able to schedule some sort of screensaver after inactivity rather than dimming the screen as they seem to think its just dropped off completely.
Would greatly appreciate if this would be considered in future updates.

**Comment by DeputyJones** [comment]
+1 for this feature too, please.  I am trying to use Xibo as the screensaver along with Kiosk but the screensaver never gets the focus.

**Comment by matt-cook** [comment]
Requested by user via email on March 8, 2017.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/enhancement-request-screensaver/104
