### ISSUE TITLE
Allow configuration file upload in Google admin console

### ISSUE THREAD

**Issue by Scooter789** [matt-cook/kiosk#177]
I want to use this Kiosk app to deploy to multiple ChromeOS devices that are enrolled in my organization. I want to be able to upload a configuration file that contains common configuration settings for all of these devices. Specifically, I want to specify the URL to show, and the username and password for the admin interface in the Kiosk app.

I'm sure others would want to control the various checkboxes available too.

I saw some other issues here that ask to control the Kiosk app via policy, but I'm not sure how to do that or if I'm missing something. As far as I know, the only way to control a kiosk app from the Google Admin Console like this is to upload a configuration file. I'm unable to do that for Kiosk.

Example screenshots are attached.
![screenshot_2](https://cloud.githubusercontent.com/assets/2989705/22515015/26d7180e-e86f-11e6-8302-019b3e23ca2c.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/2989705/22515016/26e344b2-e86f-11e6-878f-9159fc7642ee.png)

**Comment by 1951FDG** [comment]
Any update? This would be a nice to have feature!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/allow-configuration-file-upload-in-google-admin-console/102
