### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by akeilox** [matt-cook/kiosk#183]
Running the latest (as per chrome extensions site) and I see the following error when i do chrome://inspect and check the Kiosk main page;

Any idea what this might be, is there a better way to debug like a debug/log file?

Uncaught TypeError: Cannot read property 'left' of undefined
    at j (materialize.min.js:8)
    at materialize.min.js:8
    at dispatch (jquery.min.js:3)
    at r.handle (jquery.min.js:3)

**Comment by matt-cook** [comment]
This should be fixed by: https://github.com/matt-cook/kiosk/issues/210

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/error-in-console/62
