### ISSUE TITLE
Popup of Popup has blank content.

### ISSUE THREAD

**Issue by funar** [matt-cook/kiosk#189]
The application we use with Kiosk is Skyward.  The initial login screen, after successful authentication, creates a popup with the actual application inside.  The application window looks and fine.  However, when an additional popup is attempted, the window appears, but the content of it is completely blank.  

This issue does not occur when not using the Kiosk app.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/popup-of-popup-has-blank-content/101
