### ISSUE TITLE
restart dos not work on the remote host

### ISSUE THREAD

**Issue by backslashgithub** [matt-cook/kiosk#191]
"By changing the Remote Administration Host address to the wlan0 IPv4 option and changing the Port from 80 to 8080, I was able to get it to work."

I can log in and edit and save, But when i want to restart, kiosk crashes on the remote host.(the change was made, i did see this when i restart kiosk at the host)

and the option to restart the kiosk app at a set time i didn't work :-(

using raspberry, chromium and kiosk.

**Comment by Ken-L** [comment]
I am using HP chromeboxes and having a similar issue. When I try to restart the device turns off but does not turn back on. Once manually powered back on any changes that were made persist.
Chrome OS version 53 Kiosk version 5.10.

**Comment by matt-cook** [comment]
Are you still having this issue? Updates were made in v5.13.0 to address remote restart issues.

**Comment by backslashgithub** [comment]
hi there, i'am on holiday. check this when i get home...

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/restart-dos-not-work-on-the-remote-host/88
