### ISSUE TITLE
HTML5 geolocation does not work in kiosk mode

### ISSUE THREAD

**Issue by mfkp** [matt-cook/kiosk#193]
It seems that the prompt for location access is automatically rejected when running in the Kiosk app (using a chromebook). It works fine using a regular Chrome session.

You can test by using this geolocation demo: https://browserleaks.com/geo

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/html5-geolocation-does-not-work-in-kiosk-mode/98
