### ISSUE TITLE
Flash issue

### ISSUE THREAD

**Issue by dsdukes86** [matt-cook/kiosk#195]
Hi,
I've used your kiosk app last year, but this year the flash isn't working. I've enabled all the flash feature via manage content, plugins and extensions. It just says movie not loaded.

Im using a samsung chromebook, if you know of anyway to fix it can you let me know please

Cheers,

David Dukes

**Comment by michaelvelasquez** [comment]
I'm having a possibly related issue. Using a non-managed Asus Chromebit in kiosk mode with the Kiosk app set to auto-launch at startup, Flash content doesn't play and instead displays a white screen with Flash logos and the message "content on this page requires a newer version of adobe flash". This exact same Flash content, which is hosted on another computer on the same LAN plays correctly in the Chrome browser and plays in the Kiosk app when launched from the Chrome OS Launcher. But when using the Kiosk app in kiosk mode, the content won't play.

Is there a reason that the Kiosk app can display Flash content when run from the Launcher but not when the Chromebit is in kiosk mode?

**Comment by matt-cook** [comment]
Excellent question (this guy might be having the same problem: https://stackoverflow.com/questions/42496836/chromeos-56-disabling-flash-for-kiosk-app). My guess is ChromeOS disables other extensions (in this case Flash) while running in kiosk mode, though I haven't confirmed this.

**Comment by michaelvelasquez** [comment]
Thank you @matt-cook The first two solutions (SWF inside an HTML container and minimum SWF size) are already true in our case but let me see about HTTPS.
