### ISSUE TITLE
trouble saving configuration behind web filter

### ISSUE THREAD

**Issue by venuto23** [matt-cook/kiosk#196]
We've been using Kiosk for a couple years at our school district and it's awesome!  However, until now we've done the configuring of it at our district office (no issues), but today we are trying to configure 100+ Chromebooks at a school site with the URL of an online test and every time we launch Kiosk (for the first time on these devices) it seems to accept the URL of the site we want to go to and the username/password, but after saving we launch Kiosk and it returns to the configuration page.  We've tried this with several Chromebooks, 3 different models and the results are the same.  At the district office, I successfully can configure the same URL and username/password on other Chromebooks, so we have concluded the problem must be our Web Filter at that school (they have more restrictions in place then we do at the office).  Can you please tell me if there is a URL or IP address that the Kiosk configuration page saves to that we should whitelist on our Web Filter?  The Chromebooks can get to the online test page just fine, so we know that is not what is being blocked, so we are thinking that when we hit save it must be trying to go to an IP or URL to save the configuration and that is what is getting blocked.  I've been trying to comb through the web filter logs to find the IP/URL, but haven't had any luck yet.

Thanks for your great work with this app, we greatly appreciate it!

**Comment by PaulLomax** [comment]
I'm having the same issue, but we don't have a web filter...

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/trouble-saving-configuration-behind-web-filter/95
