### ISSUE TITLE
Path problem with Keynote HTML ??

### ISSUE THREAD

**Issue by exhibitry** [matt-cook/kiosk#197]
Cant get Keynote HTML to work. Cant figure out the path to enter.

I have exported HTML out of MacOS Keynote. It is in a folder on the desktop. In that folder is an index file.I can drag that index into a Chrome window and it works fine. This is the URL displayed in Chrome:

file:///C:/Users/tep/Desktop/test/assets/player/KeynoteDHTMLPlayer.html#0

I have tied variations of this with no success. Any help would be appreciated.
Reply

**Comment by matt-cook** [comment]
It's not possible to serve `file://` url's via the application. You'll need to use the "serve local content" option to select the directory you'd like to serve your files from. Then the content URL will look something like: `http://127.0.0.1:8080/KeynoteDHTMLPlayer.html`

**Comment by exhibitry** [comment]
Hi Matt, 

Thanks for the instructions. I really appreciate you taking the time to respond with such detail and I look forward to trying this out as soon as I can. I am waiting for the computers to come back from a trade show.

By the way, the method of running a web server worked fine. But obviously I would prefer not to have that complexity on the kiosks. 

One issue I was seeing was that intermittently the touch screen would be non-responsive until one touched several times. This seemed to be consistent on different computers and different touch screens. I have read that Chrome has an issue with randomly “loosing focus.” Have you seen this happen?

Tracy
