### ISSUE TITLE
Browser looses focus

### ISSUE THREAD

**Issue by exhibitry** [matt-cook/kiosk#198]
After several minutes the touchscreen (Windows 10 native - no drivers) becomes inactive and takes several touches to come back. This happens on several computers and with different touch screens. I have deactivated everything I can think of in Windows but the problem persists. 

It seems like the Chrome browser is losing focus somehow. Has anyone else run into this?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/browser-looses-focus/45
