### ISSUE TITLE
Remote administration page doesn't render correctly

### ISSUE THREAD

**Issue by jonfairman** [matt-cook/kiosk#199]
There is a bug with Kiosk 5.10.1 where the remote administration page shows up as such after logging in:
<img width="355" alt="screen shot 2017-03-13 at 2 20 22 pm" src="https://cloud.githubusercontent.com/assets/10201145/23876011/c28baa50-07f8-11e7-9281-ba9a579e4499.png">

Once you click on 'index.html' you are directed to the normal remote administration page. This did not occur in 5.10.0.

I saw this issue occur on a few Asus Chromebits we have running Kiosk in Google device managed kiosk mode (running version Kiosk 5.10.1). I had a spare Asus Chromebit on 5.10.0, and tested the remote administration page and it worked as expected. I then let it auto update to 5.10.1, tested again and the issue occurs once upgrading to 5.10.1.

**Comment by matt-cook** [comment]
Confirmed this is an issue on OSX as well.

**Comment by matt-cook** [comment]
related: https://github.com/matt-cook/kiosk/issues/166
