### ISSUE TITLE
Virtual Keyboard In Chrome Kiosk App

### ISSUE THREAD

**Issue by SlendersW** [matt-cook/kiosk#201]
Hi, 

I love what you did with the Kiosk App on Chrome. Simple, easy to use, and very effective! I was just wondering how to go about using a virtual keyboard in the app? I have a touch screen hooked up to the computer and would like to have the virtual keyboard pop up in the search bar sections. Any suggestions for how to incorporate this or do you have a backdoor code for this? Any help would be greatly appreciated!

Thanks and have a great day, 

Will

**Comment by matt-cook** [comment]
@SlendersW thanks for the request. You can follow the discussion of this feature here: https://github.com/matt-cook/kiosk/issues/53
