### ISSUE TITLE
Powers off chrome box

### ISSUE THREAD

**Issue by dwaynehopkins** [matt-cook/kiosk#203]
When I select the restart button on the Kiosk application, the chrome box powers off?

**Comment by matt-cook** [comment]
As-in it powers off and does not restart? This is definitely not behavior we've seen elsewhere. Are you using a managed Chromebox?

**Comment by dwaynehopkins** [comment]
We are in Kiosk mode

________________________________

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/powers-off-chrome-box/44
