### ISSUE TITLE
don't refresh tabs in rotate mode

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#204]
requested via email.

**Comment by bkfitz** [comment]
I think these two are basically the same... essentially separating the 'page reload' timing from the 'tab rotation' timing.

https://github.com/matt-cook/kiosk/issues/206

Thanks!

**Comment by bkfitz** [comment]
... and the same as https://github.com/matt-cook/kiosk/issues/168

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/dont-refresh-tabs-in-rotate-mode/90
