### ISSUE TITLE
make content refresh independent of loop

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#206]
requested by user via email on Dec. 30, 2016:

>  It seems like each time it loops to a new url, it has to reload the page (example: one of my pages is a Google Analytics dashboard that takes 3-4 seconds to load)… would be nice if page ‘reloads’ were triggered exclusive of ‘loop loads’… we might want to reload the page every 30 minutes or so just to keep login info alive,etc but not every 30 seconds.

**Comment by bkfitz** [comment]
This would be great thanks!

**Comment by bkfitz** [comment]
... also the same as:

https://github.com/matt-cook/kiosk/issues/168

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/make-content-refresh-independent-of-loop/89
