### ISSUE TITLE
update UI to use official material library

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#210]
Current [Materialize](http://materializecss.com/) UI is getting really clunky. Need to clean up. Probably will be based on https://github.com/material-components/material-components-web or switch to Angular: https://material.angular.io/

**Comment by matt-cook** [comment]
Ideally, I'd like to switch to using Angular.

**Comment by akeilox** [comment]
Great idea!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/update-ui-to-use-official-material-library/97
