### ISSUE TITLE
Keyboard showing on windows 8.1

### ISSUE THREAD

**Issue by mirmibrahim** [matt-cook/kiosk#213]
Hello,
 I want to use this app. but on my kiosk there is windows 8.1 as operating systme and when user click on any textbox  of any form to be filled for example contact us form. No keyboard appears whereas if i open the form on chrome and click on any textbox of form , It open the keyboard from bottom. Kindly help and suggest a way around, I need to deploy my work on kiosk in 2 days.
Regards

**Comment by P4T0U** [comment]
Hi, I've had exactly the same problem and it's related to recent versions of Chrome not working with the touch keyboard in Kiosk mode (See https://bugs.chromium.org/p/chromium/issues/detail?id=497381). I suggest you find a standalone version of Chrome 48.0.2564.116 and block Chrome auto-updates.

**Comment by matt-cook** [comment]
a virtual keyboard will also be built into the next release, which may address this issue: https://github.com/matt-cook/kiosk/issues/53
