### ISSUE TITLE
How can I access requestFilesystem?

### ISSUE THREAD

**Issue by kruny1001** [matt-cook/kiosk#214]
I know it is a bit off topic but I searched everywhere there is no right place to ask about it. I built several kiosk apps with your great kiosk app. Thank you.  One of my client keeps requesting to save video files to local device disk then run the videos for offline. So, If video playlist changes chrome app downloads new video from media server via http request then save internal space.  I guess chrome.requestFilesystem is the one that I am looking for. But it keeps return undefined for callback. Can you give some advice?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/how-can-i-access-requestfilesystem/85
