### ISSUE TITLE
autostart kiosk possible ?

### ISSUE THREAD

**Issue by backslashgithub** [matt-cook/kiosk#215]
Hi there, is it possible to start the kiosk app after you do a reboot or new startup in raspberry ?

**Comment by kadamwolfe** [comment]
I'm not sure what OS and DE you are using, but I have kiosk auto-starting using Ubuntu 16.04, running LXDE.  First, you have to enable automatic login for whatever user, and in lxsession's autostart file I put "/usr/bin/chromium-browser --profile-directory=Default --app-id=afhcomalholahplbjhnmahkoekoijban".  

Depending on your OS and DE you may not have an 'autostart' file, but they each have some method of controlling apps that start automatically at user login.

I'm not sure if the app-id is persistent across devices, but I pulled that from following the details of the 'kiosk' app added to my launcher menu.

**Comment by xinthose** [comment]
I run this command from a startup script `google-chrome --app-id=afhcomalholahplbjhnmahkoekoijban` and it works.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/autostart-kiosk-possible/82
