### ISSUE TITLE
Javascript instantiated Window does not render properly

### ISSUE THREAD

**Issue by sneakypooka** [matt-cook/kiosk#216]
I will get back here to get a screen capture to you but here is the situation:

I have javascript in the page to instantiate a new window.  When the site comes up, there is a white column across the right side running the length of the new window.   The settings for the window (in the javascript) are not being applied and this white column covers (is layered over) the content of the page.   

I am not certain this is a bug but, when not using the kiosk app, the window instantiates fine and with the proper settings.  Any assistance would be appreciated and thank you for all of your work on this application!   It is really awesome!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/javascript-instantiated-window-does-not-render-properly/83
