### ISSUE TITLE
close kiosk application via UI button

### ISSUE THREAD

**Issue by Jing-King** [matt-cook/kiosk#217]
Is there a way to close the kiosk app with a button in the app.  Like a link to /--kiosk-close

**Comment by prionator** [comment]
This would be great! If there was a way to expose it from inside JS even, like `window.closeKiosk();`.

**Comment by jayb114** [comment]
Has there been a solution completed for this?  I am running a Chromebit.  Able to get back to Admin page with CTRL-K but cannot close Kiosk app without just unplugging the device.

**Comment by Jing-King** [comment]
We use this kiosk app but we also run a Nginx and PHP server on the kiosk so when you go to URL it will run a command to kill chrome processor shutdown. And to go to the URL it is just a link.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/close-kiosk-application-via-ui-button/94
