### ISSUE TITLE
Add ignore-x-frame header

### ISSUE THREAD

**Issue by haluwong** [matt-cook/kiosk#218]
Hi All,
Is it possible to add "ignore-x-frame header" in this extension?

I have installed a "Ignore X-Frame headers" in chrome but seems this extension was ignored in kiosk mode! Please advice.

**Comment by aprilxu2222** [comment]
Has there been any updates on this?  I'm trying to display a cross-domain iFrame within the Kiosk app that has X-Frame-Options set to "sameorigin".  I've installed the same extension as haluwong on Chrome, but it's not working within the Kiosk app.  Or is there a possibility to disable X-Frame-Options with the Kiosk app? 

The Ignore X-Frame Headers extension is here: https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe/

Any help would be appreciated, thanks!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-ignore-x-frame-header/84
