### ISSUE TITLE
gifs allow right click access

### ISSUE THREAD

**Issue by TGiles** [matt-cook/kiosk#220]
When running the kiosk app, gifs are able to be right-clicked which then allows opening of new tab, save image as, copy image, and copy image address.

No other picture types seem to be affected by this behavior.

![kiosk bug](https://cloud.githubusercontent.com/assets/6314039/25678047/62d78502-3016-11e7-860e-45d46a357e41.png)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/gifs-allow-right-click-access/77
