### ISSUE TITLE
Kiosk suddenly not respecting settings

### ISSUE THREAD

**Issue by rmarque** [matt-cook/kiosk#222]
After approximately 1 week of working as expected, Kiosk no longer seems to 
acknowledge that it should: (1) I set "hide cursor"and it doesn't and (2) i set it up to refresh the content at 7:00 AM, daily and it doesn't

Anyone have any insight?

Roy

**Comment by rmarque** [comment]
Oh, yeah, running on Chromium (latest update) on Rasbian,

**Comment by loperWill** [comment]
Does it only get rid of those few settings, or does it delete all of the configuration?

**Comment by rmarque** [comment]
It does neither—the settings appear to be set, though they are not performed.

I think that it’s a disk space/cache issue: when Kiosk refreshes the content at 7:00 AM, daily, it (or chromium) seems to generate files in the chromium cache which don’t seem to be cleaned up.  The cache fills up the remaining space on the boot medium of the PI upon which I’m running chromium/Kiosk.  Is this a consequence of that fact that the PI is never rebooted/powered down?

Thanks for the response.

Roy

**Comment by matt-cook** [comment]
The caching issue should be resolved in the latest version of Kiosk.
