### ISSUE TITLE
ChromeBox Goes to sleep despite being set to not sleep

### ISSUE THREAD

**Issue by loperWill** [matt-cook/kiosk#225]
There is the setting within the Kiosk configuration to not let the Kiosk go to sleep. But, after 15 minutes, the Chromebox puts itself to sleep anyway. Is there something I am misunderstanding about the application of this setting, or is there something wrong with the Kiosk itself? Any help would be appreciated

-Liam

**Comment by j-applese3d** [comment]
I have multiple (10+) ChromeBoxes running as Kiosks. I have had only one with a sleep issue (similar to what you report) but haven't found out what is causing this. 

The rest of them work fine (don't go to sleep when told not to)

**Comment by loperWill** [comment]
j-applese3, what brand and model of chromebox do you use? Also, to be more specific, the one we have will go to sleep despite being told not to, and after an even longer period of time, it will stop responding to the mouse and keyboard and has to be manually restarted. Is that similar symptoms to the one that doesn't work for you?

Any help here is greatly appreciated!

**Comment by j-applese3d** [comment]
I haven't had time to troubleshoot the problematic chromebox as it is remote. 

Mine does wake up when providing input (as far as I can remember), so maybe it is a different issue...
It is an Asus chromebox: https://www.asus.com/ca-en/Chrome-Devices/Chromebox/
I also have used the Dell chromeboxes, but their prices went up... ;)

May want to get in touch with your vendor? Or powerwash the device (reinstall the OS)

**Comment by loperWill** [comment]
This is no longer an issue after a more recent patch, but I am still having issues with some files being kept on reset that are overloading my memory.
