### ISSUE TITLE
I installed on a Windows 7 OS. I need to change some configuraiton settings but I can't get logged in. I would uninstall, but it doesn't show up in my list of programs.

### ISSUE THREAD

**Issue by dboone8** [matt-cook/kiosk#227]

**Comment by j-applese3d** [comment]
AFAIK this is a chrome app. You don't have it installed on the OS. You can remove the extension from chrome by typing "chrome://extensions" in the address bar.

To change the configuration of the app, press Ctrl + Shift + A in the app and you should be able to change the settings.

Hope this helps.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/i-installed-on-a-windows-7-os-i-need-to-change-some-configuraiton-settings-but-i-cant-get-logged-in-i-would-uninstall-but-it-doesnt-show-up-in-my-list-of-programs/74
