### ISSUE TITLE
On-screen Keyboard Stopped Working in Kiosk Mode

### ISSUE THREAD

**Issue by atzoo** [matt-cook/kiosk#228]
I'm running the latest version on AOPEN Chromeboxes (OS 57) and the on-screen keyboard works in the normal environment when someone touches a field in the content page, but in Kiosk Mode it does not. Having the same issue if it's just google.com that is opened, so it doesn't appear to be content related. It used to work. I'm not sure what version of Kiosk or ChromeOS we were running before the issue came up.

**Comment by j-applese3d** [comment]
I would check and make sure that from the default chrome (os) login page, that the onscreen keyboard works. If not - enable it there (before logging in, bottom right -> accessibility -> onscreen keyboard).

Restart and see if the kiosk application has it as well.

**Comment by atzoo** [comment]
Thanks for getting back to me, Matt. It is turned on under accessibility and the keyboard does come up everywhere. It even comes up in your kiosk app, until you launch it in Kiosk Mode.


--

Adam Thompson
Content Producer

Zoo Atlanta
800 Cherokee Avenue SE
Atlanta, GA 30315

404.624.5923

athompson@zooatlanta.org


Stay connected:
zooatlanta.org<http://zooatlanta.org/>



[Twitter]<https://twitter.com/ZooATL>[Facebook]<https://www.facebook.com/ZooATL>[Google +]<https://plus.google.com/+ZooAtlanta/posts>[Instagram]<https://instagram.com/zooatl/>[Youtube]<https://www.youtube.com/user/ZooAtlanta1889>[Pinterest]<https://www.pinterest.com/zooatlanta/>


________________________________

**Comment by j-applese3d** [comment]
I don't have any ideas if you tried what i said earlier. It is working for me. The reason I say to check before logging in is because otherwise it is a per user setting (i think) so then it wouldn't apply to the app when in kiosk mode. If you turn it on before at the login screen i think it should be applied to all users (including the kiosk app, in kiosk mode)

PS. I'm not Matt... :)

**Comment by atzoo** [comment]
I didn't understand what you were getting at before. I didn't have a chance until this afternoon to work with that kiosk again and test your theory. The on-screen keyboard was not turned on at the login screen, but it didn't make a difference in Kiosk Mode. Thanks for the idea!


--

Adam Thompson
Content Producer

Zoo Atlanta
800 Cherokee Avenue SE
Atlanta, GA 30315

404.624.5923

athompson@zooatlanta.org


Stay connected:
zooatlanta.org<http://zooatlanta.org/>



[Twitter]<https://twitter.com/ZooATL>[Facebook]<https://www.facebook.com/ZooATL>[Google +]<https://plus.google.com/+ZooAtlanta/posts>[Instagram]<https://instagram.com/zooatl/>[Youtube]<https://www.youtube.com/user/ZooAtlanta1889>[Pinterest]<https://www.pinterest.com/zooatlanta/>


________________________________

**Comment by atzoo** [comment]
Hey all,

Got it figured out. It was a Chrome update that broke it. I had to Power Wash the device and turn on the on-screen keyboard at the network settings screen (under Accessibility) before logging in. Looks like they're not support Kiosk Mode unless you have an managed device starting with 2017 devices, FYI.

Cheers.

**Comment by geromy** [comment]
Need a solution for this also, Kiosk is great but need the option for on-screen keyboard to function in order to implement completely.  Have the device in managed kiosk mode and all is good except for no onscreen keyboard.  Running version 56 and 57 same results

**Comment by Godisr8ttan** [comment]
I have the same situation as Geromy. I think the add-on is great, but must have on-screen keyboard support, otherwise a great add-on becomes unusable for me. 

Any news regarding this?

**Comment by matt-cook** [comment]
See discussion of an on-screen keyboard here: https://github.com/matt-cook/kiosk/issues/53
