### ISSUE TITLE
New Feature: Inactivity reset only if current url different with the defined url

### ISSUE THREAD

**Issue by vincentkedison** [matt-cook/kiosk#231]
In the kiosk app, first we set the url in Content Section, for example "https://google.com"
I want the kiosk app reset back to "https://google.com" only if current url not "https://google.com". 
For example: when user search at google then they click the link to another website and they leave it (inactive) for certain time. We want the kiosk reload back to "https://google.com". But if it's inactive but the url stay in "https://google.com", it shouldn't reload.
Is it possible?
Thanks!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/new-feature-inactivity-reset-only-if-current-url-different-with-the-defined-url/75
