### ISSUE TITLE
How to turn auto off when powering down my tv

### ISSUE THREAD

**Issue by ernestowg** [matt-cook/kiosk#234]
I am trying to use this as you would a chrome app that is connected through kiosk mode.
I have kiosk mode turned on but with this app I am unable to connect it.  When i run this app, it runs non stop, even if my tv is off. I would like the app to run only when the tv is on

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/how-to-turn-auto-off-when-powering-down-my-tv/71
