### ISSUE TITLE
Keeps removing my URL & Password setup once Saved.

### ISSUE THREAD

**Issue by pjamies** [matt-cook/kiosk#236]
I cannot get it to work on a Chromebook (HP). Every time I put in a URL Link and setup a Password and hit Save, the app reboots (into the setup screen again) with everything blank. (I leave everything else blank\default).
We are using the Google Admin Console to setup the Public Kiosk Mode on this device's OU.
The device auto-launches the Kiosk app and boots into setting screen, but I cannot get settings to stay after I press the Save key.
I can get it to work on my Windows PC using this app with the same settings without an issue.
Would love to get a help screen describing what the different settings mean\do!!
Sent an email to Matt Cook, but never got a reply :(

**Comment by pjamies** [comment]
I think that I might have fixed it .. I changed some of the other settings in Google Admin Console and it seems to be working now.
Is there a way that I could get a description of all the setting options this app offers (Serve Local Content, Override User Agent, Override Authorization Header, Use of Remote Administration)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/keeps-removing-my-url-password-setup-once-saved/73
