### ISSUE TITLE
where can I update the URLs used for the kiosk app?

### ISSUE THREAD

**Issue by kadamwolfe** [matt-cook/kiosk#237]
I have need of modifying the URL(s) that the kiosk displays 'by hand'; that is to say on the filesystem.  I am using Ubuntu 16.04 and am unable to locate the config file that contains this info.
Where would this be located?  Or is it even possible?

**Comment by matt-cook** [comment]
It's not currently possible to modify the URL without accessing either the local admin or remote admin page. We are tracking the discussion of adding a better management system here: https://github.com/matt-cook/kiosk/issues/37
