### ISSUE TITLE
New Feature request

### ISSUE THREAD

**Issue by redll33** [matt-cook/kiosk#238]
It would be great if it had an option to turn on a screensaver after so many minutes and even better if it could do a slideshow and just pull the images from the default Chromebase image repository.  

Also it would be great if you could have a URL whitelist so if a website had external links on it for example facebook or twitter that it would not allow it however would allow any sites in a list.  So if you had a location finder feature that used google maps that is was allowed to display certain external content based on the whitelist.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/new-feature-request/66
