### ISSUE TITLE
delay automatic startup so wireless internet can connect

### ISSUE THREAD

**Issue by sunfire2k5** [matt-cook/kiosk#239]
Hi,

Is it possible to delay loading URL? iam having problem With no internet Connection about 50% of the time when restarting the chromebit from chrome OS and autostarting KIOSK to a specific URL.

BR,

Haakon

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/delay-automatic-startup-so-wireless-internet-can-connect/68
