### ISSUE TITLE
Configure Tab Names

### ISSUE THREAD

**Issue by danielwdunn** [matt-cook/kiosk#241]
It would be nice to be able to configure the tabs at the top of the kiosk much like bookmarks are configured normally in browsers. For example, we'd like to rename the tabs rather than getting the tab name from the HTML title. 

It would also be good to make it more obvious that the tabs are clickable -- not sure the best way to achieve that.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/configure-tab-names/70
