### ISSUE TITLE
After resetting to the home screen, multiple touches are required for the screen to respond

### ISSUE THREAD

**Issue by amirkhan81** [matt-cook/kiosk#243]
On a Windows 7 PC with a touch screen, once the kiosk app goes back to the home screen after a specified delay, multiple touches are required for the app to become responsive. This doesn't occur after any amount of time with a normal Chrome browser, only with the app.

Any ideas?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/after-resetting-to-the-home-screen-multiple-touches-are-required-for-the-screen-to-respond/59
