### ISSUE TITLE
Download file to disk

### ISSUE THREAD

**Issue by BoyStot** [matt-cook/kiosk#244]
Hi,

I'm was hoping to use this extension to help serve artwork files for users to save to a flash drive.  Is it possible to enable the downloading/saving of files?

Thanks
Stot

**Comment by loperWill** [comment]
You should be able to save files to a local drive. I have been able to(to my dismay) save files to the local storage of a Chromebox that is currently using Kiosk. You might not be able to right click and see options like on the Google browser, but you can still click a download button and be given a window with options on where to save it

Hope this helps!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/download-file-to-disk/57
