### ISSUE TITLE
"Chrome Did Not Shut Down Correctly"

### ISSUE THREAD

**Issue by ScoopDL** [matt-cook/kiosk#245]
Every 1-2 days I walk by my Kiosk display and the chromebox is off. When I restart it, it says that "Chrome did not shut down correctly."

I have the the device sleep mode disabled, but it seems that something is causing the software to crash.

**Comment by matt-cook** [comment]
This appears to be a duplicate of https://github.com/matt-cook/kiosk/issues/247
