### ISSUE TITLE
New Windows / URLS display issue (and F keys)

### ISSUE THREAD

**Issue by TimCarterLinux** [matt-cook/kiosk#246]
Hi Matt

Very impressed with "Kiosk" and would like to use it on my kiosk at work. However, my users would need to access several external websites to use it. I have the box ticked for this but find a quirk when opening up a site. I get a big blank space to the right hand side. This happens on both my chromebook (not using as a managed device) or using my Linux desktop machine.
![chrome kiosk issue popups screenshot_2017-07-02_18-16-24](https://user-images.githubusercontent.com/29841236/27772199-2d04b81e-5f55-11e7-8191-91998d3a9d73.png)

I find that on the chromebook I can press F4 twice and the space goes away
![chrombook kiosk issue screenshot 2017-07-02 at 18 09 49](https://user-images.githubusercontent.com/29841236/27772198-230fcb3c-5f55-11e7-88cd-10e1ae0a6caf.png)

Is there a fix for this?

On reset any open windows to other urls do not go away, they remain on screen?

Also I note that on the chromebook users can press F4 or F5 to get out of Kiosk?

Thanks

Tim

**Comment by matt-cook** [comment]
This issue has been resolved in v5.12.0, scheduled for release on Aug. 1: https://github.com/matt-cook/kiosk/pull/251

**Comment by TimCarterLinux** [comment]
Hi Matt, thanks for this. Have you been able to resolve the open windows to other urls issue as well as the white space?

Tim

**Comment by matt-cook** [comment]
This issue was fixed in v5.12.0. The open windows issue is tracked on a separate issue: https://github.com/matt-cook/kiosk/issues/257
