### ISSUE TITLE
Unable to Zoom page using keyboard shortcuts

### ISSUE THREAD

**Issue by deanMike** [matt-cook/kiosk#248]
Up until recently I was able to zoom in to a webpage being displayed by Kiosk using the Chrome keyboard shortcuts ctrl-+ and ctrl--. Zooming is no longer working so our the site we display on tv screens isn't readable anymore. The site supports zooming from chrome itself.

**Comment by matt-cook** [comment]
I'm surprised this worked previously. It should definitely not support the zoom shortcut keys by default. You can track the feature request to add support for this here: https://github.com/matt-cook/kiosk/issues/31
