### ISSUE TITLE
Still has mouse cursor even if it disabled

### ISSUE THREAD

**Issue by richcode** [matt-cook/kiosk#249]
By default still has mouse cursor when you don't move

**Comment by richcode** [comment]
Hi if this is software limitation then we can close this
I'm using another software AutoHideMouseCursor 2.32
to hide the cursor.

**Comment by xd1936** [comment]
I'm also having this issue. Both the "Hide Cursor" checkbox, and the webpage (using CSS `cursor:none`) are set to not show the cursor, but it's still there on boot until the mouse is moved.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/still-has-mouse-cursor-even-if-it-disabled/56
