### ISSUE TITLE
Images are not getting loaded

### ISSUE THREAD

**Issue by ercanyuz** [matt-cook/kiosk#255]
I am trying to present an Adobe Analytics Dashboard in kiosk mode. In Analytics, charts get loaded asynchronously. When I browse normally, everything is fine. In kiosk mode, the images don't get loaded. 

![bild 5](https://user-images.githubusercontent.com/6270584/28783200-da31a9fe-760f-11e7-9f66-7702175814f4.png)

I already added all relevant subdomains in whitelist. 

![bild 6](https://user-images.githubusercontent.com/6270584/28783279-2a4521b4-7610-11e7-9c06-3e6ba8dc44a3.png)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/images-are-not-getting-loaded/41
