### ISSUE TITLE
Kiosk app does not start 

### ISSUE THREAD

**Issue by Ricardotje** [matt-cook/kiosk#258]
Hi,

Since the update to 5.11 the Kiosk app does not start anymore on latest chrome OS 9460.73.1 (Official Build) stable-channel buddy. The following screen  is presented
![20170809-0112](https://user-images.githubusercontent.com/30859915/29112113-1876663a-7ced-11e7-84c7-38ddfce7d30a.png)
After an unknown long time of waiting the settings screen does appear and i need to reconfigure all of the settings of the kiosk app from scratch.
Maybe there is a solution for this issue.
And if you need more info let me know.

Keep up the good work, its a great app!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-app-does-not-start/54
