### ISSUE TITLE
URL with authentication requirements

### ISSUE THREAD

**Issue by mcheja10** [matt-cook/kiosk#26]
Gives me a 401 unauthorized.  Is this not compatible with sites requiring authentication or is there something I am doing wrong?

**Comment by matt-cook** [comment]
I'm not sure the the `<webview>` tag used by the app supports the http auth
prompt (are you referring to http authentication?). You may need to specify
the login in the URL like so: `http://username:password@example.com/`

**Comment by mcheja10** [comment]
Yes I believe so.  This is an intranet site that our organization uses that requires immediate authentication.

**Comment by matt-cook** [comment]
If you need the user to enter their own username/password you may need to create an intermediate page  with a form that will forward to the correct page with username/password specified like you see above. Currently this is untested, but we'd love to know how it works out for you.

**Comment by mcheja10** [comment]
Will keep in touch.  Thanks Matt

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/url-with-authentication-requirements/63
