### ISSUE TITLE
Chromebox retaining data even when set to clear out cache

### ISSUE THREAD

**Issue by loperWill** [matt-cook/kiosk#260]
First of all, I would like to say how happy I am with the app. After the most recent updates, it performs much better than before. 

However, one issue still remains that I haven't been able to find a resolution to. The issue is that even when the app is set to clear cache and other information, the Chromebox is still keeping some information somewhere. After signing in on the only allowed user account, I checked the storage and it was at 1.4 GB for the "other users" category while it was at 500 MB just a couple days ago. The Chromeboxes are set to reload every 3 minutes if that helps. They are used to display a PAC in the library I work at. I did notice that there was an update on August 1st that was supposed to fix this. Will the App auto update by itself, do I need to powerwash it, or is it still bug that hasn't been fixed?

Does anyone have this same problem or a solution other than powerwashing 6 managed Chromeboxes every two weeks?

**Comment by davidhelms** [comment]
@loperWill if you wouldn't mind humoring a chrome box neophyte. I'd like to check to see if we are seeing the same symptom on our boxes, but I don't know how to check the storage and see the 'other users' category and google mining hasn't turned up any gold. Mind giving me a pointer to how to do this? Thanks in advance.

**Comment by davidhelms** [comment]
per the above, nvm, I figured out where this is located in settings

**Comment by loperWill** [comment]
After viewing the storage which was steadily rising as of a few days ago, it has since stopped saving any extra data. I am unsure as to why it was doing it or why it stopped, but it did. I will make a new post/update/comment on a similar problem, should the problem arise again.
