### ISSUE TITLE
Session is not kept alive

### ISSUE THREAD

**Issue by nup002** [matt-cook/kiosk#261]
Logged-in sessions are not kept alive during a restart of the device that run the Kiosk application, when it the device is set to Kiosk mode. This new behaviour coincides well with the recent update four days ago. 

Before, if one set the Kiosk application to load a website that requires login, one only needed to login once, and check "remember me". On a restart of the device, it would immediately log in again. Now, one must login every time the device restarts. I have tested it with several websites, and it seems to be a behaviour of the Kiosk application.

**Comment by KSilverman** [comment]
I am getting the same thing. All my sessions are being terminated during a restart.

**Comment by nup002** [comment]
For my purposes, this renders Kiosk unusable. A fast fix would be greatly appreciated.

**Comment by matt-cook** [comment]
Thanks for the bug report guys. I'll be looking into this asap.

**Comment by nup002** [comment]
I found a temporary fix that also probably highlights where the problem lies:
In js/browser.js, on line 428, replacing <.attr('partition',partition)>with <.attr('partition','persist:kiosk')> solves the problem.

I cloned an older version of Kiosk that I remember working (5.11.0). However, when building an app from this older version and installing it as a kiosk app, the problem is still there. This might indicate that it is Chrome OS that has changed the way data is persisted. But I am not a developer, so this is only speculation.

**Comment by nup002** [comment]
Well, I'm stumped.
The fix I mentioned earlier does not work any more. I will experiment further and report back if I can find any stable solution.

**Comment by nup002** [comment]
I would like to present a solution that indicates the most recent stable release of Chrome OS is creating this problem. I am using an ASUS Chromebit.

What I did to get the session persistence back:
Cloned release 5.11.0 (commit 4922657bf21481aa8d8e96579010c50a95df465a) and added the following to the manifest:
 "kiosk": { 
    "required_platform_version":"9202"
  }

I then published this edited version and set the Chromebit to autolaunch it. 

With the google management platform, I allowed the Kiosk app to set the OS version number as described here: https://support.google.com/chrome/a/answer/1375678?hl=en

Reducing the Chrome OS version proved to be the only solution. I also see that a new version of the stable Chrome OS build was released the 2. August. Could be this version that broke Kiosk.

**Comment by tumbulwead** [comment]
I've just provisioned a replacement kiosk for our museum gallery for one that was malfunctioning (Acer Chromebase Touchscreen 24"), and it relies on a cookie to track its location relative to 13 others in our gallery that have been running without a problem for a year.  

This one hangs on launch ("please wait" is all that's displayed, and I have to restart it several times to get it to finally load).  It also doesn't remember the cookie across restarts (I've been scheduling one daily at 4am), so I'm guessing it's probably the same issue as this thread.  

I've made sure that all updates are current, and the behaviour is continuing.  I'd also appreciate a quick remedy to this issue, as I can't deploy these going forward with this issue at play.  

Thanks in advance for your work on this.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/session-is-not-kept-alive/33
