### ISSUE TITLE
kiosk mode, chromebit, unmanaged, does not respect settings.

### ISSUE THREAD

**Issue by kupeport** [matt-cook/kiosk#263]
hi,

Im a total newbie to chromeos. I am currently setting up a chromebit as a digital signage. 
Im on kiosk mode, but when the app loads, Im presented with the screen with no settings or url. When I exit kiosk mode on bootup, the settings are all there.

I also dont have management console or a g-suite account.

any help would be greatly appreciated. Thanks

**Comment by nup002** [comment]
You are following [this](https://www.novisign.com/blog/chrome/how-to-put-non-managed-chromebox-in-kiosk-mode/) guide? I have used this guide to set up an ASUS chromebit in kiosk mode running the Kiosk application. I also do not have a management console or any such thing. 
Can you explain in more detail what you mean with "the screen with no settings or url"?

**Comment by russellgreenwood** [comment]
I had this exact same problem - it seems like the Kiosk mode stores and remembers its own settings.  I just filled all the settings out again and now it remembers them in Kios mode - as if it’s a separate user account.

**Comment by f-langelier** [comment]
@russellgreenwood I am having the same issue but instead of the settings, it seems to not be allowing flash to run. Would you have a solution to this?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-mode-chromebit-unmanaged-does-not-respect-settings/37
