### ISSUE TITLE
Request to about:blank is blocked

### ISSUE THREAD

**Issue by bshogeman** [matt-cook/kiosk#264]
When using a Google Presentation (slides) with links to different whitelisted domains the popup shows 'Request to about:blank is blocked'. This isn't the target of the link. 'Enable New Window and Dialogs' is enabled. This issue only is an issue when using google presentation. When Google Pages is used it makes an request to google.com but works!
Also when using a Google Presentation the option 'Hide Google Slides Control' doesn't do a thing.

Further more a perfect product!!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/request-to-about-blank-is-blocked/40

**Comment by canhkieu** [comment]
I can not access your url. 404
https://discuss.kiosk.cook.company/t/request-to-about-blank-is-blocked/40
