### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by rrhutch** [matt-cook/kiosk#266]
Is there the ability to have back and forward and/or home navigation buttons with this app?

**Comment by loperWill** [comment]
Yes, you can enable a back, home, and refresh button. You can do this by going into the Kiosk setup and checking the box that says "Enable Navigation" underneath the browser section of the settings. Upon saving and reloading, the three buttons will appear in the top left corner of the screen.

Hope this helps!
![navigate](https://user-images.githubusercontent.com/28633962/29898961-7a4fdeac-8d9d-11e7-8103-8f1fe903c338.PNG)
