### ISSUE TITLE
Feature Request: Display Version on Splash Screen

### ISSUE THREAD

**Issue by davidhelms** [matt-cook/kiosk#267]
Currently it seems impossible to find the version of the kiosk app on Chrome OS anywhere other than CDM.
For reasons I won't bore you with, this is not always populated in CDM when we enrolled a device and the act of getting the Chrome OS device online to update this information to CDM generally results in the kiosk app updating itself to the latest version.
When trying to troubleshoot an issue and identify a root cause, determining the version of the kiosk app that is installed on the problem device is critical.
So a long-winded way of requesting that this information be provided locally on the device.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/feature-request-display-version-on-splash-screen/39
