### ISSUE TITLE
Blank screen when trying to serve local content

### ISSUE THREAD

**Issue by alexanderstott** [matt-cook/kiosk#269]
I have a folder of local content which works fine when I use Chrome to view it, but I just get a black screen when attempting to load it through Kiosk.

I'm using OSX on a Mac Mini. The project itself uses the Foundation 6 framework.

**Comment by anilergin** [comment]
same problem I have.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/blank-screen-when-trying-to-serve-local-content/35
