### ISSUE TITLE
Kiosk does not save account settings in Win10

### ISSUE THREAD

**Issue by gwh731** [matt-cook/kiosk#272]
Hi,

I am having a problem with Kiosk software not saving server settings so that when you restart the program or computer, Kiosk requires you to enter the Station name and server IP address.   I understand this may have something to do with how Kiosk saves its settings into the user account.  Please post a resolution ASAP.  This for University of San Diego.  

NOTE: If you are already logged into the server, then Kiosk will authenticate and work normally.  But as soon as you close the server's webpage, Kiosk no longer authenticates and you have to enter the Station name and server IP again...  :(

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-does-not-save-account-settings-in-win10/34
