### ISSUE TITLE
Kiosk App will not save Server Settings in Windows 10

### ISSUE THREAD

**Issue by gwh731** [matt-cook/kiosk#273]
TO: Matt Cook

Hi, I am having a problem with the Kiosk app not authenticating to the Kiosk server after you restart the kiosk app.  When this happens, you have to re-enter the station name and server IP address again, which will allow the app to work, but the server settings are never saved.

NOTE: When you are logged into the server, the Kiosk app then authenticates without having to enter the station name and server IP.  Please HELP!!!

Thank you,

Gary

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-app-will-not-save-server-settings-in-windows-10/36
