### ISSUE TITLE
In multiple URL mode: Extend rotate rate if there is navigate activity

### ISSUE THREAD

**Issue by viat1234** [matt-cook/kiosk#274]
My first issue on Github:
Is it possible to stop temporaraly or extend the rotate rate on a PC in Kiosk mode if some user start to navigate in the domain presented. The idea is to don't disrupt the experience with a unwanted  new URL.

**Comment by loperWill** [comment]
With the current build of Kiosk, I don't believe this is possible. :/

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/in-multiple-url-mode-extend-rotate-rate-if-there-is-navigate-activity/32
