### ISSUE TITLE
Youtube link is not opening in Kiosk - chrome os

### ISSUE THREAD

**Issue by DR651** [matt-cook/kiosk#275]
When trying to open youtube link in Kiosk app it is giving a blank page.
Opening youtube with javascript window.open("youtube.com/channel/channelid").
Please help me to solve it.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/youtube-link-is-not-opening-in-kiosk-chrome-os/31
