### ISSUE TITLE
Remote Schedule Server

### ISSUE THREAD

**Issue by olekiwanski** [matt-cook/kiosk#276]
Hi, I have a problem. I think, I'm doing everything correct, but when I send JSON code to Kiosk there is no response. So my question is : Where can I check (if it is even possible at all) where Kiosk holds items from JSON.

Thank you in advance for your response

**Comment by olekiwanski** [comment]
$tmp = array(
            "schedule" => array(
                "Value" => array(
                    "items" => array(
                        "content" => "http://www.github.com",
                        "end" => "Tue Sep 30 2017 09:30:00 GMT+0200",
                        "start" => "Wed Sep 14 2017 13:19:00 GMT+0200"
                    )
                )
            )
        );
        header('Access-Control-Allow-Origin: *');
        header('Content-Type: application/json');
        echo (json_encode($tmp));
        exit();

This is my code

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/remote-schedule-server/38
