### ISSUE TITLE
Kryptonite! Could not be mounted.

### ISSUE THREAD

**Issue by loperWill** [matt-cook/kiosk#277]
Yesterday, the Chromebox I use to run Kiosk recently wouldn't boot up. It would turn on and only display a black screen. After trying to get it to boot up and load Kiosk for a little bit, I gave up and powerwashed it. After re enrolling it, Kiosk would start to load and would then close and then give me the error "Kryptonite! The cryptohome for the kiosk application could not be mounted." 

I have attached a picture of the error below.
![20170926_133859](https://user-images.githubusercontent.com/28633962/30883532-4e0ee32c-a2c1-11e7-9d8b-7dff8c3fd10b.jpg)

**Comment by xd1936** [comment]
I've started getting these also. Some are freshly set up Chromeboxes, others randomly do it after working fine for years.

**Comment by loperWill** [comment]
There is a solution to this. You have to force your Chromebox to go into a recovery mode. This can be done by unplugging the power connector from the Chromebox while it is booting up multiple times until it goes into recovery. The reason that powerwashing the device doesn't help is because the cryptohome files don't get checked or erased upon doing so as they aren't user generated files. In recovery, it checks all of these system files and will repair the cryptohome files since they have become corrupted.

**Comment by loperWill** [comment]
I decided that since this might be a problem for others, I should probably leave the issue open, at least for a little while.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kryptonite-could-not-be-mounted/30
