### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by QuantumTaoist** [matt-cook/kiosk#278]
I enter the URL and tweak a couple of settings, then save.  The chrome restarts, I open Kiosk app and we are back at the beginning, Kiosk asking for the URL again all my settings gone.

Am I missing a step?

**Comment by loperWill** [comment]
If your Chrome device is managed, then you have a setting enabled that will do this. Go to Device Management -> Chrome -> Device Settings. Under the sign in settings, there is the option to erase local user data after each sign out. Set this to "Do not erase all local user data." Make sure to save your settings, and restart the Chrome device to ensure that it rechecks for these changes. After configuring the Kiosks settings, they should now save successfully.

**Comment by loperWill** [comment]
Other than that cause, which happened to me, I don't have a idea for a better solution.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/settings-are-not-saved/67
