### ISSUE TITLE
Print dialog coming up twice

### ISSUE THREAD

**Issue by robp2175** [matt-cook/kiosk#281]
When I type Ctrl+p the print dialog comes up twice. For example, I will print the document, then the dialog will come up again. Any thoughts?

**Comment by robp2175** [comment]
I reverted back to 5.13.1 and this is no longer a problem. This issue was introduced somewhere within the last couple of commits.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/print-dialog-coming-up-twice/29
