### ISSUE TITLE
[Feature Request] Option to Clear Cache on Reboot

### ISSUE THREAD

**Issue by xd1936** [matt-cook/kiosk#282]
This Chrome App is awesome. We use it mainly for Digital Signage. We are able to remotely reboot our signage devices, but sometimes things get stuck in cache. It would be great if we didn't have to lug out our keyboard and mouse to the physical device just to clear the cache!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/feature-request-option-to-clear-cache-on-reboot/25
