### ISSUE TITLE
Kiosk app "Enable New Windows and Dialogs" disabling issue

### ISSUE THREAD

**Issue by kylepickel** [matt-cook/kiosk#283]
We are using the kiosk app for a new project we implemented but it wont work without clicking the "enable new windows and Dialogs" button. After a certain amount of time this button is still checked but you have to push the save button at the bottom. Once this happens we are able to use the app correctly. Is there a way that we can make this not happen? It basically after so long needs to be re-enabled again.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-app-enable-new-windows-and-dialogs-disabling-issue/26
