### ISSUE TITLE
New feature request: add auto-login

### ISSUE THREAD

**Issue by lukavyidi** [matt-cook/kiosk#284]
День добрый, как сделать автовход для пользователя. Первичная страница требует ввод логина и пароля.
Требуется автозаполнение формы.

**Comment by matt-cook** [comment]
Google translate:
> Good day, how to make an auto-login for the user. The primary page requires entering a login and password.
Autocomplete form is required.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/new-feature-request-add-auto-login/50
