### ISSUE TITLE
Problems with connection to other websites/applications

### ISSUE THREAD

**Issue by erwinschools** [matt-cook/kiosk#29]
Hello,

I installed the KIOSK app from Zebradog and this works fine BUT the webpage I wantto show is just a page with other links on it. 
A certain amount of these links simply don't open. Has anyone an idea how what causes this and how to solve this ?

Kind regards,
Erwin

**Comment by matt-cook** [comment]
Hi Erwin. Are these pages opening as new tabs or pop-ups? Currently these
are blocked.

**Comment by erwinschools** [comment]
Hi Matt,

The pages are indeed opening as new pages.
Will there be a new version in the near future ?

Kind regards,
Erwin

Op maandag 29 juni 2015 heeft Matt Cook <notifications@github.com> het
volgende geschreven:

> Hi Erwin. Are these pages opening as new tabs or pop-ups? Currently these
> are blocked.
>
> On Monday, June 29, 2015, erwinschools <notifications@github.com

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/problems-with-connection-to-other-websites-applications/81
