### ISSUE TITLE
Set zoom factor

### ISSUE THREAD

**Issue by ImproDrake** [matt-cook/kiosk#31]
Hi all,

It would be great if it could be possible to set a zoom factor for the page you're showing in Kiosk. Is that a possible future feature?

Kind regards,
   Marc

![](https://api.bountysource.com/badge/issue?issue_id=23769218)

**Comment by matt-cook** [comment]
Hi Marc,

Thanks for the request. It's certainly possibly, but not currently a planned feature. We've had success doing something similar by creating a wrapper page with an iframe and css scaling applied.

**Comment by ImproDrake** [comment]
Thank you for your quick replay. I guess a wrapper also works. Thanks! :)

**Comment by matt-cook** [comment]
Re-opening since we've had another request for this feature.

**Comment by lrdezines** [comment]
If the management allowed to set zoom percentage it'd work great. -- ie 75% zoom per Chrome.  

refining the zoom level via keyboard command would also work - "command" & "+" or "-"

**Comment by viquac** [comment]
This is exactly what I need as well.  Is it still being worked on?   Right now, my webpage is showing up zoomed in.  I can't see the whole page.

**Comment by matt-cook** [comment]
This isn't a feature I've needed for a billable project, so it's not under active development currently. It  certainly has not been forgotten though, if anyone is interested in sponsoring I'd be happy to make it happen.

@viquac zoom shouldn't be applied at all by the Kiosk app. So if your application is showing zoomed inside Kiosk, and doesn't normally I'd like to help debug further.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/set-zoom-factor/92
