### ISSUE TITLE
Reset time entered is altered by an hour

### ISSUE THREAD

**Issue by matt-schuh** [matt-cook/kiosk#32]
E.g. if I say to restart at 4pm (16:00) the program sets it to restart at 3pm (15:00)

**Comment by matt-cook** [comment]
@matt-schuh do you know if this has been resolved?

**Comment by matt-schuh** [comment]
Probably related to DST.  I think the code chops off an hour regardless of DST or not.

**Comment by matt-cook** [comment]
probably a duplicate of: https://github.com/matt-cook/kiosk/issues/151
