### ISSUE TITLE
add all admin options to remote admin page

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#33]
Currently only shows restart, url, and username/password.

**Comment by matt-cook** [comment]
holding on this. pending #89

**Comment by jbergler** [comment]
@matt-cook would you consider adding a separate option that allows users to enable the full settings if they want to accept the risk on a non-ssl page?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-all-admin-options-to-remote-admin-page/61
