### ISSUE TITLE
manage settings via policy

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#37]
Similar to Chrome Sign Builder app: https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/wuAIcgugy38/tDzShGiKrOMJ

**Comment by matt-cook** [comment]
official policy format: http://www.chromium.org/administrators/configuring-policy-for-extensions

**Comment by matt-cook** [comment]
scheme defined here: https://developer.chrome.com/extensions/manifest/storage

**Comment by matt-cook** [comment]
currently no way to debug this locally without management console: http://stackoverflow.com/questions/23555197/how-do-i-define-a-policy-value-for-a-chrome-extension-using-the-managed-storage

**Comment by matt-cook** [comment]
branch specific to this issue: https://github.com/zebradog/kiosk/tree/config-upload

**Comment by NoSubstitute** [comment]
Any hope of this becoming a reality any time soon?
Setting up a room, or many rooms, full of Chromebooks and students, five minutes before exam commences, using the manual method isn't quite going to cut it.

There needs to be a way to tell the Kiosk where to go, without touching each and every Chromebook. Well, really setup all settings.

I should just have to move them to the right Kiosk OU.

**Comment by matt-cook** [comment]
We're working on this currently, it won't be in the version we're releasing this month but is a fairly high priority. If you need it sooner, [please contact us](mailto:support@zebradog.com).

**Comment by NoSubstitute** [comment]
Any progress?

**Comment by trevoriancox** [comment]
I have got this working for the settings: 'url', 'host','port','username','password'. But in an @matt-cook 's branch work on this started on the 'schedule' setting  only:

https://github.com/zebradog/kiosk/commit/076d35e2b2f676b7403dc613f84871443cb6c2e9 

Shall we clarify for this issue what settings are intended?

**Comment by trevoriancox** [comment]
Another spec question:  Should group policy override chrome.storage.local, or chrome.storage.local override group policy?

**Comment by matt-cook** [comment]
thanks @trevoriancox! This has been pretty high on the priority list for a while. I'd suggest we follow Microsoft's group policy precedence order: https://technet.microsoft.com/en-us/library/cc785665(v=ws.10).aspx and allow group policy to override local. 

Feel free to submit a PR whenever it looks good.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/manage-settings-via-policy/153
