### ISSUE TITLE
Use behind required proxy seems to break configured site access

### ISSUE THREAD

**Issue by dansut** [matt-cook/kiosk#49]
It appears that URL loaded by webview does not use network connection proxy, instead attempts to access direct and fails if it can't. Tried with both automatic and manual proxy configuration.

**Comment by matt-cook** [comment]
Having never used a proxy to load content, I'm a bit unclear on the process for this. Do you set the proxy in network settings and then it's not respected by the <webview> in the Kiosk app? 

Appears it could be related to this issue: https://code.google.com/p/chromium/issues/detail?id=172285

Possibly we'd need to add additional permissions, or UI elements to manage proxy settings (https://developer.chrome.com/extensions/proxy).

**Comment by dansut** [comment]
After a bit of further investigation - creating my own super basic kiosk app based on tutorial - it seems problem is perhaps not in your code at all; webview is ignoring the selected network proxy setting, in the version of Chrome I'm using anyway, 45.

My ultimate desire is to have the proxy auto-detected, this is not the default so even this config is similar to specifying a proxy. How this is done depends on whether CrOS system is enrolled or not - presently testing without my Chromebox enrolled and it involves selecting in network settings before logging in, then again for specific user once logged in (after Ctrl-Alt-K), it's a pain and being enrolled makes easier but I suspected there were problems with that so I was trying to simplify...

I had seen the Chromium issue that you point out, and although it is related it seems the desire there is more complex than the simple behaviour I want - which is to follow the currently in-use setting. The desired behavior of that issue is to be able to specify a special proxy for the App/Webview - I just want it to follow the rules as the rest of CrOS seems to be doing at the time.

Using the API you point out it looks like should be possible to give the app a different proxy config, or query what is currently in use - however I can already see in the proxy log CrOS is using correct proxy, it just seems the webview tries to access direct. If direct is possible it works, if it isn't then it fails and unfortunately when I go live with this the proxy will be the only way out from the Kiosks on the CrOS LAN.

I'm fairly new to the whole Chrome App dev environment but will to try anything out to help debug and find a solution that works for me and in turn may make your useful app even more widely usable, any pointers would be appreciated

**Comment by dansut** [comment]
It seem that creating a kiosk app with [Chrome App Builder](https://chrome.google.com/webstore/detail/chrome-app-builder/ighkikkfkalojiibipjigpccggljgdff) has exactly the same issues when required to use a proxy... it doesn't, I'm guessing webview is buried in there somewhere but it is deep within foam.js and to be honest it all seemed like too much code to achieve what this app does better so I didn't even look.

**Comment by dansut** [comment]
Just updated to CrOS dev channel (46) and that has exactly the same symptoms. I guess the next thing I need to do is work out where I need to post what I'm seeing to see if I can get it confirmed as a bug (or feature with no docs and diagnostics), maybe find a workaround and possibly in the future get a fix implemented.

**Comment by dansut** [comment]
I have created a [question on Stackoverflow](http://stackoverflow.com/questions/32487520) to try and get to the bottom of the behavior I have documented here.

**Comment by matt-cook** [comment]
Upvoted. Definitely keep us posted on what you find.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/use-behind-required-proxy-seems-to-break-configured-site-access/148
