### ISSUE TITLE
enable dialog boxes

### ISSUE THREAD

**Issue by snagytx** [matt-cook/kiosk#52]
Really nice extension, while using it on a ChromeBox I have the customers fill-in a form, on submit I need to show an alert, this doesn't seem to be working in kiosk mode. Is this something that can be implemented/fixed?

Thank you

**Comment by matt-cook** [comment]
Thanks! This request is being tracked in #6. Currently it's not enabled so the recommended solution is to use a javascript/css modal pop-up inside your application page.

**Comment by matt-cook** [comment]
Re-opening. Dialogs may be handled differently than pop-up windows and tabs.

**Comment by matt-cook** [comment]
Prompts are now enabled in version 5.8.0. Needs more work to get prompt and confirm types working. 

Docs: https://developer.chrome.com/apps/tags/webview#event-dialog
Test page: http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt

**Comment by matt-cook** [comment]
Prompt and confirms requested by user via email on Mar. 1, 2017. Also:

> when the dialog is displayed it should wait before continuing the code.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/enable-dialog-boxes/49
