### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [matt-cook/kiosk#53]
Hi! we will be running this on a touch enabled device but we won't have a real keyboard, so I need to have a virtual keyboard on screen...
Chrome's virtual keyboard extensions seems to do a great job, is there a way to integrate Kiosk and these extensions ?
I can't make js virtual keyboards (like thishttps://github.com/Mottie/keyboard/) work on my framework (Im using MeteorJS)

Thanks

**Comment by matt-cook** [comment]
Currently, our recommended solution is implementing this in your application. It sounds like that won't be an option for you (and we understand there may be other users in  your situation) so I'll leave the issue open, though it's not currently a high priority item for development.

**Comment by johnnydevs** [comment]
+1 for this feature

**Comment by Roofwah** [comment]
+1 also

**Comment by matt-cook** [comment]
Thanks for the votes guys. Good to know what's needed. Currently this feature still isn't on our roadmap ( since we don't have a project currently requiring it). If you'd like to expedite it, you can place a bounty here: https://www.bountysource.com/issues/26840896-virtual-keyboard or contact us directly: support@zebradog.com

**Comment by matt-cook** [comment]
Should test with 3rd party app:

https://chrome.google.com/webstore/detail/virtual-keyboard/pflmllfnnabikmfkkaddkoolinlfninn

(suggested by user in Chrome App Store)

**Comment by matt-cook** [comment]
Possibly we could use this in conjunction with a "hidden" button or other mechanism (swipe/hold/other-more-obscure-gesture/etc?) to allow users to open the admin without plugging in a keyboard.

**Comment by mattrq** [comment]
Please allow the linked Keyboard
+1

**Comment by cuervopunk** [comment]
+1 this is the only thing preventing us from using kiosk

**Comment by jadus** [comment]
The virtual keyboard extension works great, but sadly it does not open in kiosk mode...
Did someone manage to get it work ?

**Comment by cuervopunk** [comment]
Nope

**Comment by faster-77** [comment]
+1

**Comment by jonastcne** [comment]
+1

**Comment by matt-cook** [comment]
Requested by a user via email on Feb. 8, 2017.

**Comment by ghprod** [comment]
:+1:

**Comment by harryn** [comment]
+1

**Comment by cwicaksono** [comment]
Hi, i was try using some extension for virtual keyboard but not working. Maybe will be great features if Kiosk can integrated with custom virtual keyboard like this one

https://github.com/sdeering/onscreenkeyboard

**Comment by ria-stamopoulou** [comment]
+1

**Comment by knobo** [comment]
Would it be possible to load an external extension in the kiosk app, to enable a virtual keyboard? The in-web-page-jquery-keyboard is not always a solution.

**Comment by matt-cook** [comment]
@knobo unfortunately, no. It's not possible to load an extension into an app, as far as I know.

**Comment by Odianosen25** [comment]
@matt-cook pls any word on when this feature will be available? Running Windows 10, on a Linx 8 Tablet and want to use it as an interface into my system.

Thanks

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/virtual-keyboard/150
