### ISSUE TITLE
enable pop-up windows

### ISSUE THREAD

**Issue by pdrreid** [matt-cook/kiosk#6]
Is there any way to allow dialogue boxes and popups?

The site I'm trying to kiosk has a couple of buttons that bring up dialogues / pop-ups like 'Are you sure you wish to cancel?', and these are currently disabled. 

![](https://api.bountysource.com/badge/issue?issue_id=4287608)

**Comment by xd1936** [comment]
Any movement on this? Pages with a "Sign In with Google" button won't work because the pop-up doesn't pop-up. I tried adding `"contentSettings.popups",` to the manifest, but no luck.

**Comment by matt-cook** [comment]
@xd1936 Not yet. It hasn't been an issue on any of our billable projects so it keeps getting bumped down in the queue.

**Comment by xd1936** [comment]
What is an overview of the changes that would need to be made? Is it just a manifest thing?

**Comment by matt-cook** [comment]
The manifest update suggestion above is probably not applicable. Likely it would need to be handled by an event listener, as suggested here: https://groups.google.com/a/chromium.org/forum/#!msg/chromium-apps/zzGLSiyWCnM/dMBcPBW2BUcJ

similar to how we handle permission requests for webcam/mic: https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L159

**Comment by matt-cook** [comment]
New branch has been created with initial work on pop-up windows: https://github.com/zebradog/kiosk/tree/popup

These can be fairly complex, so likely we'll add support for simple dialogs prior to new windows or tabs: #52

**Comment by xd1936** [comment]
@matt-cook This is great news! All I need is support for Google sign-in buttons, which cause a pop-up window to open and ask the user to log-in.

**Comment by xd1936** [comment]
I checked out the `popups` branch and tested it out, and Google sign-in buttons launch the sign-in screen right now perfectly, in full screen. After the user logs in, however, the pop-up does not go away and close itself, leaving the user with a blank full-screen window.

**Comment by matt-cook** [comment]
@xd1936 does the latest version 5.8.0 work for you? I've added support for new windows.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/enable-pop-up-windows/149
