### ISSUE TITLE
Possible Daily Restart Feature Bug

### ISSUE THREAD

**Issue by bfleishman** [matt-cook/kiosk#62]
I have 5 ASUS Chromeboxes running the latest general release firmware. Each are set to Kiosk mode and automatically launch the KIOSK app when starting up and they are programmed to display URL.

I enabled the "Daily Restart" feature with the default 4am setting and we noticed that the Chromebox devices would actually poweroff at that time frame period. We have a camera on 4 of the Chromeboxes and we recorded video of the units just turning off at that specified daily restart time.

We have since disabled that feature in the KIOSK app settings and this behavior is no longer occurring.

**Comment by matt-cook** [comment]
Thanks for the note! Unique that you were able to actual document that.. very helpful.

Did you notice if it was off consistently? Perhaps a time zone issue or similar.

**Comment by matt-cook** [comment]
Wasn't able to reproduce, due to #86. Removing milestone, but will keep open until #86 is resolved and this can be tested.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/possible-daily-restart-feature-bug/146
