### ISSUE TITLE
app doesn't display in 'Windows 8 Mode'

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#64]
as reported in app store:

> > > Hi, this is the screenshot of the Chrome in Windows 8 mode.
> > > The Kiosk app is not visible:
> > > http://oi66.tinypic.com/o7rb4k.jpg

**Comment by akeilox** [comment]
Is there any way to make this work with Windows 8.1 Assigned Application - aka Kiosk mode?

I would like to hide the Charm Bar access on the Windows 8.1 tablet.

**Comment by matt-cook** [comment]
@akeilox we ran into this issue recently. Apparently you need 8.1 Enterprise to do this since Chrome is a "Classic" Windows app: https://technet.microsoft.com/en-us/library/mt219050(v=vs.85).aspx

We worked around this by creating a batch script (@kstangel do you recall the details?) that closed Explorer on start up. Windows 10 doesn't appear to have the same issue with the Charm bar.

**Comment by matt-cook** [comment]
@kstangel, found your script:

```
TIMEOUT /T 10
taskkill /f /IM explorer.exe
```

**Comment by kstangel** [comment]
That's correct. By killing explorer on startup you can avoid the charm menu or any menu on Win 8. The timeout in the script is to allow explorer to fire up the kiosk app before killing explorer. 

As for Win 10, the charm menu does not exist, although you can still reach other menus by swiping from the corners/sides so you can use the script above or try using a third-party application such as http://www.classicshell.net/

**Comment by akeilox** [comment]
Thanks for the feedback and tip guys, appreciated!

I have created a shortcut for Kiosk chrome app, move it to Startup folder of an auto-login kiosk user.

For this .bat file, what is the best way to execute it? Putting it alongside the startup folder or ?

**Comment by kstangel** [comment]
I placed it alongside the kiosk app in the startup folder. The 10 second timeout specified in the BAT file will insure that the kiosk application launches first.

**Comment by akeilox** [comment]
I was testing it with the previous bat script, and wondering why charm bar was still showing up earlier today:

@echo off
taskkill /F /IM explorer.exe
explorer.exe
exit

Now, noticed the script is updated, explorer is not being called after being terminated. Just updated remotely the batch file to this

@echo off
TIMEOUT /T 20
taskkill /F /IM explorer.exe

Not able to test if the charm bar is showing up with this script (testing via Radmin remotely), but really hoping this gets rid of the swipe-left charm bar completely.
I have put it in the same startup folder with the kiosk shortcut as well, and restarted. All looking fine remotely.

I increased the timeout to 20, as its a rather old atom tablet, rather clunky - to be on the safe side.

**Comment by akeilox** [comment]
Just a quick update, I have tested the
TIMEOUT /T 20
taskkill /F /IM explorer.exe

on the physical machine today and it indeeds kills the charm bar, and finally it works like a real kiosk in Windows 8.1.

Many thanks to @matt-cook and @kstangel for highlighting the Windows Enterprise/AssignedApp limitation and sharing a simple and efficient work-around.

Merry Xmas!

**Comment by matt-cook** [comment]
Glad you got it going! Merry Christmas!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/app-doesnt-display-in-windows-8-mode/119
