### ISSUE TITLE
Home/Forward/Back/URL Navigation

### ISSUE THREAD

**Issue by johnnydevs** [matt-cook/kiosk#66]
Hi,

Is it possible to show the 'Home' button. Or even the 'Forward/Back' navigation?

Perhaps I am missing it and it's really obvious!

![](https://api.bountysource.com/badge/issue?issue_id=28358985)

**Comment by matt-cook** [comment]
Currently this isn't a feature of the Kiosk app. Our recommended solution is implementing the forward/back/home button inside your application (possibly via an iframe). 

Implementing browser/application functionality into the Kiosk app isn't currently a development priority, but we have been getting similar requests so that may change at some point.

**Comment by johnnydevs** [comment]
Thanks for the advice. Unfortunately I can't implement the buttons inside an iframe (or at least don't know how to!). My 'app' is a stand-alone kiosk, a simple touch screen monitor with a browser and internet access.

**Comment by jonastcne** [comment]
We are using touch screens on 50 installations and would really like this feature!

**Comment by Ken-L** [comment]
I don't believe there is a home button but i am able to navigate with F1 (back) and F2 (forward)

**Comment by matt-cook** [comment]
URL bar also requested via email on April 4, 2017.

**Comment by Dirton** [comment]
Hi, I just want to add, That we ended up using you plugin as well after trying mKiosk on FF. FF even out of the box doesn't support swipe gesture to do a "back" command. We really miss the standard chrome swipe function on your extension. It seem to be such a must have feature to have gestures enabled navigation when using kiosk on touchscreen in full screen mode, strange nobody realized it up until now. We will looking forward  for v5.12.0 very much. Thank you for your awesome effort!

**Comment by matt-cook** [comment]
This feature was added in v5.12.0.
