### ISSUE TITLE
reload on top-level 404

### ISSUE THREAD

**Issue by billboule** [matt-cook/kiosk#72]
- usecase : you have a self-hosted webapp running as kiosk without any internet connexion.
- in your app you have external links which cannot be loaded. If you click on one of them, you are stucked (no :back button)

look at the code of the extension "customize error page" here : https://chrome.google.com/webstore/detail/customize-error-page/bhjbejfffcjgacmeflfkmkadnfiihnpj?utm_source=chrome-app-launcher-info-dialog

//Adding a Listener to Error Occured Event
chrome.webNavigation.onErrorOccurred.addListener(function (details) {
    // Updating the browser window with desired URL

```
chrome.tabs.update(null, {
    url: "http://localhost/coopclient/index.php"
});
```

});

Could you integrate that code in your app so that we go back to the "default content url" when an error page occur ?

Thank you so much !

**Comment by matt-cook** [comment]
Thanks for the request. We should be able to extend our solution for #25 and reset automatically on a failed load: https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L166

Need to investigate how this is implemented for an app. It appears `webNavigation` may only apply to extensions: https://developer.chrome.com/extensions/webNavigation
(related?: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-apps/PTu0XDtkfGs)
Probably can use `webRequest` + 
https://developer.chrome.com/apps/tags/webview#type-WebRequestEventInterface

**Comment by matt-cook** [comment]
Will test with: http://httpstat.us/404

**Comment by billboule** [comment]
Thanks matt for keeping that on the way...

**Comment by matt-cook** [comment]
This could be done via the [WebRequestInterface](https://developer.chrome.com/extensions/webRequest). Unfortunately this requires wildcard host permissions which would [trigger a warning](https://developer.chrome.com/extensions/permission_warnings) for existing users. 

We'll need to add a checkbox to the admin to enable this feature, which will then [prompt for the additional permissions](https://developer.chrome.com/extensions/permissions).

**Comment by mogmarsh** [comment]
I've been dealing with this issue as well. In my case, the server threw a 502 error and the kiosk got stuck on the error page. I wrote an [extension](https://chrome.google.com/webstore/detail/autorefresh-on-error/cacnfebiodkggmdjhecdkendmeimjioa) that will attempt to reload the page after 60 seconds if the http response code is not 200. It works fine in regular Chrome, but doesn't work in the Kiosk.

Am I missing something on getting the extension to work in the Kiosk or are extensions not supported?

Thanks!

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/reload-on-top-level-404/141
