### ISSUE TITLE
option to hide scroll bars

### ISSUE THREAD

**Issue by amattn** [matt-cook/kiosk#79]
Currently using kiosk app with a chrombox on a 1080p TV.

source is a dashboard/BI website.  the scroll bars are visible and both ugly and potential sources of burnin.

I actually see two sets of scroll bars for some reason... disappearing rounded flat rects on both horiz and vert.  and a vertical only scrollbar just outside that doesn't disappear...  

![](https://api.bountysource.com/badge/issue?issue_id=29495561)

**Comment by matt-cook** [comment]
If possible, the easiest way to resolve this is by setting `overflow:hidden` on the body of your dashboard website. 

Alternatively, we could add this as a feature (https://developer.chrome.com/apps/tags/webview#method-insertCSS). Currently it's not a high priority item for us, but you're welcome to contact us directly (support@zebradog.com) for a quote or simply place a bounty on it: https://www.bountysource.com/issues/29495561-option-to-hide-scroll-bars

**Comment by lrdezines** [comment]
Full-screen presentation mode a with no scroll bars or sidebars is very desirable

**Comment by vizion8-dan** [comment]
Hi, 
hiding scrollbars would be awesome. Actually I use a Chrome flag to enable #overlay-scrollbars  (chrome://flags/#overlay-scrollbars) which does not hide the scrollbars but makes them nearly invisible ;-)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/option-to-hide-scroll-bars/143
