### ISSUE TITLE
secure remote admin page

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#89]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

for devices on unsecured networks.

**Comment by matt-cook** [comment]
Could possible also use: https://developers.google.com/identity/protocols/OpenIDConnect

or continue to use basic auth if SSL can be added: https://github.com/kzahel/web-server-chrome/issues/8

**Comment by kzahel** [comment]
This could also be done with chrome.gcm securely.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/secure-remote-admin-page/139
