### ISSUE TITLE
kiosk mode hangs on unmanaged device

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#94]
> We are trying to use your Kiosk App on an ASUS Chromebit (Chrome OS device) and have followed the instructions on the following website:
> 
> https://support.google.com/chromebook/answer/3134673
> 
> The issue we have is that at the login screen, we click on the Apps icon on the shelf and select Kiosk and then it opens up to a full screen window with the Kiosk app icon and “Please Wait”…this screen never changes, so we are not sure what we are doing wrong.
> 
> We went through all the settings in the Kiosk app when we were logged into the Chrome OS with our admin account, but we can’t seem to get it to launch in the Single App Kiosk mode.

Reported as happening on un-managed chromebit.

**Comment by trehn** [comment]
The same thing happens to me on an unmanaged Chromebit with the official "Chrome Sign Builder" app. So it might not be your fault at all. Sometimes it says "Please Wait", sometimes "Initializing application...". Still sucks, of course.

Let me know if there is anything I can do to help debug this.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/kiosk-mode-hangs-on-unmanaged-device/48
