### ISSUE TITLE
Double click and touchscreen

### ISSUE THREAD

**Issue by sweetsixteen** [matt-cook/kiosk#96]
Hello,

Got a weird issue here: I'm displaying a web page on a touchscreen, and the dblclick() jQuery event is not triggered on Kiosk mode if I'm using the touchscreen (double click with a mouse works fine).

The issue doesn't appear if I'm launching the same page in a regular Chrome window. 
Tested with the https://api.jquery.com/dblclick/ demo 

Any ideas?

**Comment by matt-cook** [comment]
Interesting, sounds like the `<webview>` tag we use to embed the page may behave slightly differently than desktop browser. We will try to reproduce this on our end. 

Low priority for us currently since we don't generally use dblclick for our applications.

**Comment by kstangel** [comment]
This might be related to what I'm seeing at one of our installs. I am having weird issues where we lose touch but I can bring up the webpage in chrome and touch work. Also mouse interaction works both in kiosk (when touch doesn't work) and on the webpage

I'm investigating

**Comment by guilcorp** [comment]
Related issue here.
Web page with one iframe embed. I'm loosing touch capability on my main frame when multi touching go through different frames. Touch work on Windows but touch events are not responding on the frame.

like @kstangel no problem with mouse, actually it even "reset" correctly the touch.

Any workaround?

**Comment by kstangel** [comment]
We use a large touch-frame overlay for our touch device. I have noticed if the Kiosk Application launches before the touch frame is powered on or initialized we won't receive touch events in our application. 

The Kiosk Application needs to be restarted to receive touch events again. This may NOT be related to the Kiosk Application, could also be the website. However I though I might mention it.

Make sure touch devices are initialized and powered on before launching the Kiosk Application.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/double-click-and-touchscreen/125
