### ISSUE TITLE
loosing settings after power loss

### ISSUE THREAD

**Issue by tehb544** [matt-cook/kiosk#97]
i`m using chrome os on raspberry PI, after  power loss system loading Kiosk app, but without all setting - it starting the kiosk setup page.

not every time, some times it works fine.

does anybody got something like this?

**Comment by elcarone** [comment]
Same problem over here! On multiple devices...

**Comment by matt-cook** [comment]
Thanks for the bug reports guys. That's definitely a bug. Very important that the system be able to recover automatically from power loss.

Any additional details you can provide would be helpful:

- How long you have you been using the app?
- How long have you been having the issue?
- @elcarone what OS are you running? If ChromeOS, managed or un-managed?

**Comment by matt-cook** [comment]
Looks very similar to this known issue with ChromeOS: http://www.novisign.com/chrome/what-is-google-cryptohome-bug-of-chromebox-chromebit/

**Comment by elcarone** [comment]
Matt,

Not that issue I think.
Problem only seems to happen when I enable Remote Administration. If i do
not enable this the kiosk is fine with no resets. Any ideas?

Ronald

2016-03-28 23:09 GMT+02:00 Matt Cook <notifications@github.com>:

**Comment by elcarone** [comment]
Unfortunately the settings did reset after all. But it seems to happen
faster if Remote administration is enabled. The first 4 reboots were fine.

2016-03-29 9:05 GMT+02:00 Ronald Leenders <roonleenders@gmail.com>:

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/loosing-settings-after-power-loss/129
